### ISSUE TITLE
need to add download page of Apache APISIX

### ISSUE THREAD

**Issue by moonming** [apache/apisix-website#10]
Apache APISIX has the Apache release now: https://dist.apache.org/repos/dist/release/incubator/apisix/0.9/, so we need to add download page like https://shardingsphere.apache.org/document/current/en/downloads/

**Comment by juzhiyuan** [comment]
will be published tonight

**Comment by juzhiyuan** [comment]
https://apisix.incubator.apache.org/downloads/
