### ISSUE TITLE
bug: URGENT docs/download is stale but was used in 2.1 announce email

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix-website#100]
The announce email for 2.1 links to
http://apisix.apache.org/docs/downloads/
which does not include the 2.1 release.

Either fix the docs/download page, or set up a redirect from /docs/download/ to /download/

**Comment by juzhiyuan** [comment]
I just transferred this issue here.

cc @sebbASF @moonming

**Comment by moonming** [comment]
ping @juzhiyuan

**Comment by juzhiyuan** [comment]
ok, will fix it tomorrow morning.

**Comment by juzhiyuan** [comment]
quick fix by https://github.com/apache/apisix-website/commit/702bf8165ffdde4c2af515c6d56d70530a089e35

**Comment by juzhiyuan** [comment]
related issue https://github.com/apache/apisix-website/issues/104
