### ISSUE TITLE
docs: remove rc text from Release Guide

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#106]
https://apisix.apache.org/release-guide/#make-source-code-package-and-upload-to-apache-svn

Related Email: `[VOTE] Release Apache APISIX Dashboard 2.2 RC1`

![image](https://user-images.githubusercontent.com/2106987/102002039-a709dd00-3d33-11eb-9399-3ab42feebff7.png)

cc @membphis @moonming

**Comment by juzhiyuan** [comment]
This Guide's example is confusing, we may remove the `rc` text.

**Comment by idontknowjs** [comment]
@juzhiyuan do you want it like this `mkdir 1.0 && cd 1.0` or all the `rc` in the file
