### ISSUE TITLE
Ambiguous dates in web pages

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix-website#112]
The web pages use dates of the form:

10/12/2020

Such dates are ambiguous.
It could either mean Oct 12th 2020 (in the US) or Dec 10th 2020 (elsewhere)

Numeric-only dates should use the form:

yyyy-mm-dd

Alternatively, the month should be spelt out.

**Comment by moonming** [comment]
@juzhiyuan please take a look

**Comment by juzhiyuan** [comment]
ok

**Comment by KishaniKandasamy** [comment]
Hi juzhiyuan,
To resolve this issue , Can I remove  **enableUpdateTime: true**, from **siteConfig.js**  and go for another alternative solution to display the last updated date?

**Comment by juzhiyuan** [comment]
Not only enableUpdateTime, something like Download Page or other pages, need to be updated as well. Maybe we should first search this framework's community?

**Comment by KishaniKandasamy** [comment]
Yeah .Thanks.

**Comment by juzhiyuan** [comment]
done
