### ISSUE TITLE
host website by Apache APISIX

### ISSUE THREAD

**Issue by moonming** [apache/apisix-website#154]
apisix.apache.org is hosted by apache server now, can we host by Apache APISIX?

**Comment by juzhiyuan** [comment]
Ticket: https://issues.apache.org/jira/browse/APISIX-20

**Comment by juzhiyuan** [comment]
Just created a new one under Infra project.

https://issues.apache.org/jira/browse/INFRA-22393

**Comment by juzhiyuan** [comment]
**Update**

The Infra team moved all websites behind the Fastly Service as CDN, it may cause the slowdown for Chinese, and need more discussion on that ticket., see https://issues.apache.org/jira/browse/INFRA-22393

**Comment by juzhiyuan** [comment]
Won't fix by Infra. https://issues.apache.org/jira/browse/INFRA-22393?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
