### ISSUE TITLE
add feature and users section in homepage

### ISSUE THREAD

**Issue by moonming** [apache/apisix-website#155]
The current homepage is too simple, need to add some Apache APISIX features description.
And Apache APISIX has many users such as https://github.com/apache/apisix/issues/487, if we can add all logos and links of users will be great.

**Comment by moonming** [comment]
and `Events & News` section too

**Comment by juzhiyuan** [comment]
- [x] Fulfill the logo wall on the Homepage;
- [x] Added Events on the Homepage & navbar refer to http://skywalking.apache.org/
