### ISSUE TITLE
adjust images' dimention

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-website#158]
![image](https://user-images.githubusercontent.com/72343596/105866991-8a014300-602f-11eb-8c8c-9e20b71e5b42.png)

**After upgrading to V2, Here is some CSS that needs to be changed：**
1. The default font color of the navigation is `#fff`
2. the image width needs to be deleted~

Thanks~

**Comment by KishaniKandasamy** [comment]
> ![image](https://user-images.githubusercontent.com/72343596/105866991-8a014300-602f-11eb-8c8c-9e20b71e5b42.png)
> 
> **After upgrading to V2, Here is some CSS that needs to be changed：**
> 
> 1. The default font color of the navigation is `#fff`
> 2. the image width needs to be deleted~
> 
> Thanks~

Hi,
[1]: The default font color of the navigation is `#fff`(mentioned here)

I think [1] is  a work in progress in docusaurus V2 (https://github.com/facebook/docusaurus/issues/3937)

Thanks.

**Comment by juzhiyuan** [comment]
Yes, it's related to V2.
