### ISSUE TITLE
Visit Downloads page without docs prefix

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-website#159]
Now
![image](https://user-images.githubusercontent.com/72343596/105868307-03e5fc00-6031-11eb-81f8-ed02465e2ea1.png)

TODO
Navigation links need to be slightly modified ,like: 
1. `/docs/downloads`  to `/downloads`
2. `/docs/team` to `/team`

such as:
![image](https://user-images.githubusercontent.com/72343596/105869067-d0f03800-6031-11eb-9269-d73c06135cb9.png)

Thanks

**Comment by juzhiyuan** [comment]
This issue relies on #157, should resolve #157 first.

**Comment by juzhiyuan** [comment]
#157 is fixed, go ahead.
