### ISSUE TITLE
feat: be compatible with mobile devices

### ISSUE THREAD

**Issue by sysulq** [apache/apisix-website#161]
![image](https://user-images.githubusercontent.com/1734615/106721335-7f523980-663f-11eb-9489-45ee4c4a8040.png)

**Comment by tokers** [comment]
@juzhiyuan @LiteSun .

**Comment by juzhiyuan** [comment]
fine, this site is refactored days ago, once we deployed it, I will have a try on mobile.

**Comment by juzhiyuan** [comment]
done
