### ISSUE TITLE
bug: the docs link is broken

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-website#168]
**Actual Behaviour**

The `/docs` link is broken with 404 returned.

**Expected Behaviour**

We could see docs in official website.

**Steps to reproduce it**

1. Access `http://apisix.apache.org/docs/`;

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/2542401/107142782-30bcdc00-696c-11eb-8cc6-649089ea3cc4.png)

**Comment by imjoey** [comment]
Hi @KishaniKandasamy , would you like to tackle this issue? Thanks. 😃

**Comment by KishaniKandasamy** [comment]
Sure :)

**Comment by imjoey** [comment]
> Sure :)

@KishaniKandasamy , great and please let me know if I can do anything. Looking forward to your PR. Thank you very much.
