### ISSUE TITLE
add committer page and team page

### ISSUE THREAD

**Issue by moonming** [apache/apisix-website#19]
for example:
https://shardingsphere.apache.org/community/en/contribute/committer/
https://shardingsphere.apache.org/community/en/team/

**Comment by juzhiyuan** [comment]
Noted, I will handle this this week.

**Comment by juzhiyuan** [comment]
If it's urgent, please let me know.

**Comment by moonming** [comment]
get all ppmc and committer info from: https://whimsy.apache.org/roster/ppmc/apisix#ppmc
