### ISSUE TITLE
Put all static files under this repo

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#196]
Hi, we need to put all static files (e.g images in blog) under this repo and could use `jsDelivr` to speedup the visit.

**Comment by juzhiyuan** [comment]
~~and @qier222 will take this issue.~~

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Could you guide me how to approach this issue?

**Comment by juzhiyuan** [comment]
Ya, for now, we have all static files like images put on the CDN (outside this repo), we need to put them in our repo first.
