### ISSUE TITLE
add community page

### ISSUE THREAD

**Issue by moonming** [apache/apisix-website#20]
refer to https://shardingsphere.apache.org/community

**Comment by juzhiyuan** [comment]
- [x] [Subscribe Guide](https://apisix.apache.org/zh/contribute/subscribe/)
- [x] Contributor Guide
- [x] Committer Guide
- [ ] Code of Conduct
- [ ] Documents Contributor Guide
- [x] Release Guide
- [x] 2FA

**Comment by juzhiyuan** [comment]
DONE
