### ISSUE TITLE
Enhancement: fix visible breakages in website UI on mobile, PNG logo is pixelated and other changes for better UX. 

### ISSUE THREAD

**Issue by 1502shivam-singh** [apache/apisix-website#212]
<h3>Actual behaviour</h3> 
Currently the website looks fine, but I have some changes to recommend. Currently the animation text in top hero section overflows to 2 lines when “high-performance” (image 1) comes up, and leading words have some margin from left breaking alignments (image 2 and 3)
<br></br>

<strong>image 1</strong>
![Apache_before_mobile2](https://user-images.githubusercontent.com/57267960/109315764-e34bd480-7870-11eb-8f65-e13a8a09632d.png)
<br></br>

<strong>image 2</strong>
![Apache_before_mobile1](https://user-images.githubusercontent.com/57267960/109315355-78020280-7870-11eb-8a46-1c92c35478c9.png)
<br></br>

<strong>image 3</strong>
![InkedApache_before_mobile1_LI](https://user-images.githubusercontent.com/57267960/109316311-7e44ae80-7871-11eb-8143-6ffe167682e8.jpg)

The PNG logo on navbar is pixelated and can be replaced with a SVG logo. (image 4) 
<br></br>

<strong>image 4</strong>
![Apache_before_mobile_nav](https://user-images.githubusercontent.com/57267960/109316485-adf3b680-7871-11eb-9d1f-05f8501320f5.png)

Also the button sizes and spacing on mobile are  not appropriate as a bigger size button would be better on mobile for touch and the buttons stick together vertically, here some spacing would be better.  (image 5)
<br></br>

<strong>image 5</strong>
![InkedApache_before_mobilebuttons_LI](https://user-images.githubusercontent.com/57267960/109316847-09be3f80-7872-11eb-8b9c-867eca7048f0.jpg)

<h3>Expected behaviour</h3>

The expected result in the text animation in top hero is to keep the animated word in one single line, because overflow could break the text animation’s grey background leading to not so good results.

For the logo, as I have said above a SVG logo would be better as its modern, doesn’t pixelate and saves file size.

The buttons should be little bigger, than the current variant with some more padding. Also there should be proper spacing between the buttons to prevent mistouch.

<h3>Steps to reproduce</h3>

The text animation can be kept in one line by changing the word “high-performance” to a word with same meaning and smaller lexically. I recommend using “Performant” as it’s a synonym of “high-performance” ([source](https://www.wordhippo.com/what-is/another-word-for/high-performing.html)). I personally have tested this word and it fits properly (check image below). For the extra margin a blank space after the space character did the trick.

As far as the logo is concerned, I have designed three versions of your org’s logo as a SVG, you can check them here ([Figma link](https://www.figma.com/file/LeICU6ikwITGemfw8lBRs3/APISIX-Apache-swf?node-id=0%3A1)) and tell which one you like.

CSS changes will do the trick for the buttons. Appropriate margins and padding.

<h3>After change screenshots</h3>
Fixing text animations (image 6) and alignments (image 7) (due to margins) -
<br></br>

<strong>image 6</strong>
![Apache_After_mobile2](https://user-images.githubusercontent.com/57267960/109317172-733e4e00-7872-11eb-9402-6ce2cd342efd.png)
<br></br>

<strong>image 7</strong>
![Apache_After_mobile1](https://user-images.githubusercontent.com/57267960/109318042-63733980-7873-11eb-984a-102a685af6a7.png)

After changing logo to SVG in one of the given options and changing title font-size to match logo size (image 8)-
<br></br>

<strong>image 8</strong>
![Apache_After_mobile_nav](https://user-images.githubusercontent.com/57267960/109317451-bc8e9d80-7872-11eb-9d89-a23745f962b2.png)

Changing button sizes, paddings and spacings (image 9) -
<br></br>

<strong>image 9</strong>
![Apache_After_mobile1](https://user-images.githubusercontent.com/57267960/109317652-efd12c80-7872-11eb-942d-3818c2e7be03.png)

@juzhiyuan I would like to take up this issue, as I have already done the necessary work to solve this issue. Also, if the figma link doesn't work in your country (maybe) for some reason, then please tell me I will share them here as images.

**Comment by qier222** [comment]
How about we make "View on GitHub" button and "Download" button as wide as screen width on mobile devices？

**Comment by 1502shivam-singh** [comment]
I feel the size in image 9 is fine. Making them full width would pull way too much attention to them and it breaks hierarchy and layout. As of hierarchy we should have focus hierarchy like this according to me : "Apache Apisix.......Gateway" > buttons > "Provides rich.........etcd."

**Comment by qier222** [comment]
This is my solution: I add a ` <br />` element between "Dynamic" and "Cloud-Native", only on mobile devices.

<img width="448" alt="CleanShot 2021-02-27 at 01 13 37@2x" src="https://user-images.githubusercontent.com/68148142/109332433-0db18800-7899-11eb-9d26-65b9e15a0ae4.png">
<img width="389" alt="CleanShot 2021-02-27 at 01 13 56@2x" src="https://user-images.githubusercontent.com/68148142/109332484-2326b200-7899-11eb-8099-f8ad0b87e725.png">

**Comment by 1502shivam-singh** [comment]
Okay, so you also reduced the font-size for the heading (looks like to me) for high-performance to fit in, I am looking at keeping the original font size as it's better suited for hierarchal difference between the hero text and main heading. 

The idea of using the `<br/>` tag only on mobile is a good idea 😄 to solve that small gap issue and incidentally I also used this method 😂😂, before stumbling over the fact that a leading space did the trick too.

Regarding the full width buttons as I said, usually it's preferred that CTA (call to action) buttons should be less than 70% of the actual mobile device width, specially when you have more than one CTA buttons. Full width buttons are recommended when they are the only action that the user is supposed to take on the whole screen (example - App onboarding screen, you would have seen this too, buttons on bottom are full width).
![test](https://user-images.githubusercontent.com/57267960/109347143-ad224b00-7898-11eb-933c-564e52271543.png)

The less than 70% because consider the situation of a miss-tap when scrolling on mobile. Having some free space with no interactive elements around helps in scrolling.



And thanks for attending my small lecture on button user experience design 🤣🤣🤣
