### ISSUE TITLE
add more projects to /docs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#216]
Hi, we have a project-homepage here[1], and we need to add more projects to this page.

**Projects**
- [apisix-helm-chart](https://github.com/apache/apisix-helm-chart)
- [apisix-docker](https://github.com/apache/apisix-docker)

[1] https://apisix.apache.org/docs/

**Comment by akshitadixit** [comment]
Hello may I work on this?

**Comment by juzhiyuan** [comment]
Of course, and we could do #218 first :)

**Comment by stu01509** [comment]
Hi @juzhiyuan 

I would like to try this issue.

**Comment by juzhiyuan** [comment]
Hi, you may need to implement other issues first 😂

**Comment by stu01509** [comment]
> Hi, you may need to implement other issues first 😂

Let me solve this issue haha.

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Should I use `sync-docs.js` to sync the apisix-helm-chart and apisix-docker project documents?
If yes, I think we need to move those projects's `xxx.md` files to `/docs` folder right?

**Comment by juzhiyuan** [comment]
yep! you are right!
