### ISSUE TITLE
check and fix all broken links

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#217]
Hi, we get some feedback from the community that we have broken links in our projects 🤔 anyone would like to have a check and fix them?

**Comment by mtwn105** [comment]
Hi I will give it a try @juzhiyuan

**Comment by juzhiyuan** [comment]
great!

**Comment by juzhiyuan** [comment]
When u have any problems, kindly cc me :)

**Comment by mtwn105** [comment]
I will send list of links which are failing after checking all @juzhiyuan

**Comment by mtwn105** [comment]
Link | Location | Error
---- | ---------- | ------
https://apisix.netlify.app/docs/apisix | Navbar -> Docs -> APISIX | 404
https://apisix.netlify.app/docs/dashboard | Navbar -> Docs -> APISIX Dashboard | 404
https://apisix.netlify.app/docs/ingress-controller/design | Navbar -> Docs -> APISIX Ingress Controller | 404
https://apisix.netlify.app/zh/docs/apisix | Navbar -> Docs -> APISIX (ZH language) | 404
https://apisix.netlify.app/zh/docs/dashboard | Navbar -> Docs -> APISIX Dashboard (ZH language) | 404
https://apisix.netlify.app/zh/docs/ingress-controller/design | Navbar -> Docs -> APISIX Ingress Controller (ZH language) | 404
https://github.com/apache/apisix/blob/master/CHANGELOG.md | Navbar -> Downloads | 404
https://kubernetes-sigs.github.io/service-apis/ | Navbar -> Blog | 404
dev@apisix.apache.org | Navbar -> Docs -> General -> Release Guide | No "mailTo:" at the start of the email link
https://github.com/apache/apisix-website/blob/master/docs/download.md | Navbar -> Docs -> General -> Release Guide | 404

These are links I managed to find which seems to be broken.

@juzhiyuan Please send me correct links so I can fix them. 👍

**Comment by juzhiyuan** [comment]
Hi,

1. `/docs/apisix` is in progress;
2. `/docs/dashboard` is in progress;
3. `/docs/ingress-controller` should under the `apisix.apache.org/xx`;
4. `CHANGELOG` is in fix;
5. You could add `mailto` :)
6. `/docs/download` should be `/download

**Comment by mtwn105** [comment]
Hi @juzhiyuan Fixed the two issues. Opened PR #219 

For `mailto` one, I just put email there as markdown will take care of it.
