### ISSUE TITLE
The column button takes too much spaces for phone layout

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#223]
What we got:
![微信图片_20210302113239](https://user-images.githubusercontent.com/34589752/109593032-3f517a00-7b4b-11eb-939c-65eb5b171d81.jpg)

What it should be (take chaos mesh website for reference):
![微信图片_20210302113230](https://user-images.githubusercontent.com/34589752/109593066-4a0c0f00-7b4b-11eb-8fa6-5dcc891f57f0.jpg)

**Comment by juzhiyuan** [comment]
ya, this is just fixed :) ✌️

**Comment by juzhiyuan** [comment]
just checked and fixed it already
