### ISSUE TITLE
The top `version` is not set for phone layout

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#224]
What we got:
![image](https://user-images.githubusercontent.com/34589752/109592396-298f8500-7b4a-11eb-9580-0416f03cbf3b.png)

What it should be (take chaos mesh website for reference):
![image](https://user-images.githubusercontent.com/34589752/109592425-38763780-7b4a-11eb-8787-a4b1f4e7ed7f.png)

**Comment by stu01509** [comment]
Hi @Yiyiyimu 

I want to try this issue, Please assign this issue to me :)

**Comment by stu01509** [comment]
Hi @juzhiyuan 

I knew the version info is wrapped by **DocsVersionDropdownNavbarItem**, but where can I found more detail about this?

https://github.com/apache/apisix-website/blob/master/website/src/theme/DocSidebar/index.js#L191-L193

**Comment by qier222** [comment]
> Hi @juzhiyuan
> 
> I knew the version info is wrapped by **DocsVersionDropdownNavbarItem**, but where can I found more detail about this?
> 
> https://github.com/apache/apisix-website/blob/master/website/src/theme/DocSidebar/index.js#L191-L193

Check out this
https://v2.docusaurus.io/docs/next/using-themes#swizzling-theme-components
https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme/NavbarItem

**Comment by stu01509** [comment]
> > Hi @juzhiyuan
> > I knew the version info is wrapped by **DocsVersionDropdownNavbarItem**, but where can I found more detail about this?
> > https://github.com/apache/apisix-website/blob/master/website/src/theme/DocSidebar/index.js#L191-L193
> 
> Check out this
> https://v2.docusaurus.io/docs/next/using-themes#swizzling-theme-components
> https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme/NavbarItem

Thanks for your information, I will take a look.
