### ISSUE TITLE
improve the description for users to join Slack

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#229]
Hi, we have a Slack channel for users to discuss.

*Homepage -> Footer*
![image](https://user-images.githubusercontent.com/2106987/109619717-1396ba00-7b74-11eb-8dcc-1744e7f63f2a.png)

*[Help](https://apisix.apache.org/help)*
![image](https://user-images.githubusercontent.com/2106987/109619798-24dfc680-7b74-11eb-80f0-1017195cd180.png)

Here have 2 issues:
1. We should update the link to `https://join.slack.com/t/the-asf/shared_invite/zt-lcbw4olf-_5s17RLU0Cx8xTvj2bNbjg`, or users have to use `@apache.org` account to join.
2. We should tell users that they need to search `#apisix` channel, or they will only see `#welcome` channel after joining in.

**Comment by ashwindevx** [comment]
Hi, @juzhiyuan I'm interested in this issue. But can you provide some more info on it? 

Like do you want to have a pop up to tell the user to "search `#apisix` channel, or they will only see `#welcome` channel after joining in."

**Comment by juzhiyuan** [comment]
@qier222 What do you think on `popup`?

**Comment by qier222** [comment]
> @qier222 What do you think on `popup`?

Popup sounds good to me.

**Comment by juzhiyuan** [comment]
@qier222 Could you give some more detailed suggestions or steps? then @ashwindevx could work on it :)

**Comment by ashwindevx** [comment]
@qier222 ?

**Comment by qier222** [comment]
I haven't used Slack, I can't help you with this right now, sorry.

**Comment by juzhiyuan** [comment]
@ashwindevx Hi, could we add a mouseover tip for it? or add some text description?

**Comment by juzhiyuan** [comment]
after searching some OSSs, we could tell users that `Joining the #apisix channel in the ASF Slack workspace.` is fine

**Comment by ashwindevx** [comment]
@juzhiyuan I think a mouseover tip/note will be fine. Just tell me the text you want to have there.

![Group 2](https://user-images.githubusercontent.com/59074550/109912916-047a4e00-7cd3-11eb-9882-6a1e40d1aeb7.png)

**Comment by juzhiyuan** [comment]
Kindly search #apisix after you are in.


How about this one?

**Comment by ashwindevx** [comment]
Kindly search the #apisix channel to get access to all the channels.

How about this? You should tell the user what searching the #apisix channel will do.

**Comment by juzhiyuan** [comment]
good for me!

**Comment by ashwindevx** [comment]
Cool, assign the issue to me.

**Comment by ashwindevx** [comment]
I can't find the `index.html` file. Which folder has the `help` page?

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-website/tree/master/website/src/pages

**Comment by moonming** [comment]
how about `http://s.apache.org/apachecon-slack` as the slack link?

**Comment by moonming** [comment]
> We should update the link to https://join.slack.com/t/the-asf/shared_invite/zt-lcbw4olf-_5s17RLU0Cx8xTvj2bNbjg

Will this link become invalid after some time?

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/109988106-2bbc3400-7d42-11eb-8358-b2daf6dc21f2.png)

As far as I know, it will expire in over 30 days.

@ashwindevx Please use this one `https://join.slack.com/t/the-asf/shared_invite/zt-mrougyeu-2aG7BnFaV0VnAT9_JIUVaA` instead./

**Comment by ashwindevx** [comment]
Sorry man. I don't know React yet. I thought the code was in JS. All the code is in react. I don't think I can fix this issue.

**Comment by juzhiyuan** [comment]
1. https://github.com/apache/apisix-website/blob/master/website/src/pages/help.js#L71
2. add `<a title="xxxx">TEXT</a>`
