### ISSUE TITLE
docs: tell users where they are

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#230]
Hi, when I visit docs like https://apisix.apache.org/docs/apisix/getting-started , I have no idea which project I am in 🤔 anyone could help to add a more clear tip on which project I'm reading?

![image](https://user-images.githubusercontent.com/2106987/109627405-8efc6980-7b7c-11eb-9403-7b0be9e3e3e4.png)

**Comment by iamayushdas** [comment]
Could you elaborate more?

**Comment by juzhiyuan** [comment]
oh sure, as you could see, when we see no matter the `APISIX` docs or `APISIX Dashboard` docs, users may get confusing because they couldn't know which project they are reading. We could add the Project name here or other places.

![image](https://user-images.githubusercontent.com/2106987/110402881-226ef680-80b7-11eb-878d-078f42d4d8cd.png)

**Comment by iamayushdas** [comment]
oh got you

**Comment by juzhiyuan** [comment]
Hello~ any update about this?

**Comment by iamayushdas** [comment]
i am not working on this right now. i am working on plugin from dashboard

**Comment by juzhiyuan** [comment]
ok, anyone would like to take this?

**Comment by iamayushdas** [comment]
Can you give me last two hours to solve this?
If i won't be able to do i will tell you

**Comment by stu01509** [comment]
Hi @juzhiyuan 

If @iamayushdas not able to solve it, I would like to try it :)

**Comment by iamayushdas** [comment]
@stu01509 can you help me in this please?

**Comment by stu01509** [comment]
Hi @iamayushdas 

Actually, I'm not get in-depth about this issue, What problem do you encounter?

**Comment by juzhiyuan** [comment]
@iamayushdas Hi, please refer to https://v2.docusaurus.io/ first :)

**Comment by iamayushdas** [comment]
> @iamayushdas Hi, please refer to https://v2.docusaurus.io/ first :)

Okay

**Comment by iamayushdas** [comment]
https://github.com/apache/apisix-ingress-controller/pull/316 have i done this right. i am not sure.
i have read the documentation of Docusaurus as suggested by @juzhiyuan .

**Comment by iamayushdas** [comment]
i think we should close this now @juzhiyuan what say?

**Comment by juzhiyuan** [comment]
oh yes
