### ISSUE TITLE
the doc url is wrong

### ISSUE THREAD

**Issue by soulsoul** [apache/apisix-website#231]
https://github.com/apache/apisix-website/blob/7d3064da0047bb2c838ae877866c1d3e1b3fa6ef/website/src/pages/help.js#L50

the url is missing

![image](https://user-images.githubusercontent.com/4963471/109632535-15677a00-7b82-11eb-81ab-41d2c0c95faf.png)

**Comment by juzhiyuan** [comment]
oh yes, and the correct one is ` href="https://apisix.apache.org/docs"

**Comment by juzhiyuan** [comment]
Would you like to send a PR to fix it?

**Comment by soulsoul** [comment]
> Would you like to send a PR to fix it?

ok

**Comment by dhawal-kamdar** [comment]
Can I fix this issue?

**Comment by dhawal-kamdar** [comment]
@soulsoul can I fix this issue please or you have started working on this?

**Comment by juzhiyuan** [comment]
Hi @dhawal-kamdar you could resolve this one when you are free :)

**Comment by dhawal-kamdar** [comment]
Thank you @juzhiyuan 
I will fix it.

**Comment by dhawal-kamdar** [comment]
Hello @juzhiyuan I have fixed this issue. please, check it https://github.com/apache/apisix-website/pull/233
