### ISSUE TITLE
Missing plugins doc of apisix shown in website

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#236]
Say `request-id`, we could find it in [doc](https://github.com/apache/apisix/tree/master/docs/en/latest/plugins/request-id.md) of apisix repo, but not in the website

**Comment by juzhiyuan** [comment]
ya, anyone would like to send a PR and add that plugin to this file? https://github.com/apache/apisix/blob/master/docs/en/latest/config.json

**Comment by Yiyiyimu** [comment]
Actually there are 44 English plugin docs in apisix repo, but we only got 32 doc on website. And maybe we need to provide some more suggestions on which part the missing docs are belong to 😁

**Comment by juzhiyuan** [comment]
🤔 ok, @guoqqqi, please check which plugins are missing, and list them out first. Then we could cc @spacewander to take a look at which type they belong to.

**Comment by guoqqqi** [comment]
https://docs.google.com/document/d/17lN3JOEKlMefDWfH5Wpny5WXl_QeViR15RMqDyryQNc/edit
Hi, I've counted some of the missing plugins here, please help me to see how to classify them, and then I will fix them.

**Comment by juzhiyuan** [comment]
Hi, would you please paste them in issue, too?

**Comment by dhawal-kamdar** [comment]
According to my counting, there are **44 plugins** in apisix repo out of which **10 plugins** are missing in the config.json file.
I have also noted the names of the missing plugins, now the only thing to figure out is which plugin falls under which category?
Please help.

**Comment by juzhiyuan** [comment]
@spacewander Hi, would you help to sort them out? then @dhawal-kamdar would help to add them.

**Comment by spacewander** [comment]
Done

**Comment by juzhiyuan** [comment]
Thanks!

**Other protocols:**
- dubbo-proxy
- mqtt-proxy

**Security:**
- consumer-restriction

**General:**
- echo
- server-info

**Loggers:**
- error-log-logger
- sls-logger

**Authentication:**
- hmac-auth

**Monitoring:**
- node-status

**Traffic：**
- request-id

**Comment by dhawal-kamdar** [comment]
Hello, @juzhiyuan and @spacewander thanks for sorting the plugins.
I just have one question should I add missing plugins in the starting or in the ending.

for example,
echo, server-info plugins comes under General.
But should I add them before "plugins/batch-requests"
or after plugins/redirect
![sc](https://user-images.githubusercontent.com/55776390/109912912-02b08a80-7cd3-11eb-953b-63e2c19bcaa3.jpeg)

**Comment by juzhiyuan** [comment]
Both are ok, only need to make sure they are under the correct category:)

**Comment by dhawal-kamdar** [comment]
Okay, I will fix this issue 👍🏻

**Comment by dhawal-kamdar** [comment]
@juzhiyuan can you help me with this
**Is this PR backward compatible?** If it is not backward compatible, please discuss on the mailing list first


![cc2](https://user-images.githubusercontent.com/55776390/109923111-5081be80-7ce4-11eb-958d-100694d31037.jpeg)
