### ISSUE TITLE
fix the sidebar missing of apisix-ingress-controller design doc

### ISSUE THREAD

**Issue by tokers** [apache/apisix-website#243]
**Actual Behaviour**

When we open the design page of apisix ingress controller doc site, we don't see the sidebar there.

**Expected Behaviour**

 

The sidebar should be shown. the [config.json](https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/config.json), should add an item to record the `design`, for instance:

```json
    {
      "type": "category",
      "label": "How It Works",
      "items": [
          "design"
      ]
    }
```

**Steps to reproduce it**

 

**Screenshots of the issue**

 

![image](https://user-images.githubusercontent.com/10428333/110073528-7c6f7380-7dba-11eb-8446-edd2293e9aad.png)

**Would you like to work on the issue?**

**Comment by batman-ezio** [comment]
@tokers   https://apisix.apache.org/docs/ingress-controller/getting-started/ looks good to me. fixed?

**Comment by tokers** [comment]
Yes, it was fixed.
