### ISSUE TITLE
docs: added event about releasing APISIX 2.4

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#246]
Hi, we just released Apache APISIX 2.4, we could add an event for this.

1. See https://github.com/apache/apisix/blob/master/CHANGELOG.md#240 
2. Add a new event here: https://github.com/apache/apisix-website/tree/master/website/events

**Comment by 1502shivam-singh** [comment]
![image](https://user-images.githubusercontent.com/57267960/110241146-504c2200-7f75-11eb-83c8-bf5a2a310c99.png)

In this should I replace the ver-2.3 event with the current ver-2.4 event in above image, or keep it for some legacy check if someone is still using the old one? 


![image](https://user-images.githubusercontent.com/57267960/110241229-b46ee600-7f75-11eb-8868-c1a088bcb9ba.png)

Just made a past of ver-2.3 for review
TO:DO - Fill in the latest version release guide

**Comment by qier222** [comment]
You should remove the oldest event on the homepage. @1502shivam-singh

**Comment by 1502shivam-singh** [comment]
![image](https://user-images.githubusercontent.com/57267960/110241937-9f945180-7f79-11eb-8658-6399fa719495.png)
I am only showing the first four events in the events array now, following the previous code pattern, with events sorted by date.
_**Can you tell me the exact date when this version-2.4 was released?**_

**Comment by 1502shivam-singh** [comment]
> You should remove the oldest event on the homepage.

Was just writing when you commented, done

**Comment by juzhiyuan** [comment]
Hi @1502shivam-singh, the release date is `2021-03-05` :)
