### ISSUE TITLE
incorrect powered-by.md link

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#250]
Hi, would you mind fixing this link in this PR?

The correct one is `https://github.com/apache/apisix/blob/master/powered-by.md`

_Originally posted by @juzhiyuan in https://github.com/apache/apisix-website/pull/239#discussion_r589125799_

**Comment by stu01509** [comment]
Anyone is working on this issue?

**Comment by juzhiyuan** [comment]
it sees that @KishaniKandasamy is working on this 😂

**Comment by KishaniKandasamy** [comment]
> it sees that @KishaniKandasamy is working on this 😂
 😐😐

**Comment by juzhiyuan** [comment]
@KishaniKandasamy aoh!! I made a wrong cc 😂
