### ISSUE TITLE
Action: check broken links after building

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#255]
**Actual Behaviour**

Hi, I noticed that there have some broken links here[1], could we have a GitHub Action to check after building?

[1] https://apisix.apache.org/docs/ingress-controller/getting-started/#installation-on-cloud

**Comment by stu01509** [comment]
Maybe we can [markdown-link-check](https://github.com/tcort/markdown-link-check) to check our link?

**Comment by juzhiyuan** [comment]
This action may get banned by ASF due to security reasons 🤔 You could have a try.

**Comment by bzp2010** [comment]
@juzhiyuan
May I ask, is this problem caused by the relationship between relative path and absolute path? I want to try to fix this problem.

**Comment by juzhiyuan** [comment]
I haven't tried on them for now, could we first add a link checker in CI?

**Comment by bzp2010** [comment]
> I haven't tried on them for now, could we first add a link checker in CI?

I will try it.

**Comment by bzp2010** [comment]
Currently, I have implemented a prototype and submitted a PR. It is still in draft. #263

**Comment by bzp2010** [comment]
Today, PR has submitted some new code, which is basically available. #263
