### ISSUE TITLE
brokens links in installation docs about apisix-ingress-controller

### ISSUE THREAD

**Issue by tokers** [apache/apisix-website#256]
![image](https://user-images.githubusercontent.com/10428333/110798287-f5883280-82b4-11eb-838c-9cf2ed77f929.png)

The links here are broken, should be fixed. For instance, links about Install Ingress APISIX on Azure AKS (https://apisix.apache.org/docs/ingress-controller/getting-started/docs/en/latest/deployments/azure.md) should be changed to https://apisix.apache.org/docs/ingress-controller/deployments/azure/, and others are similar.

**Comment by stu01509** [comment]
Let me fix it :)
