### ISSUE TITLE
invalid URLs in translation docs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#259]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, we have contributors who noticed that there have some broken links in translated docs:

e.g.: https://apisix.apache.org/zh/docs/apisix/discovery/
and this doc is targeted to https://github.com/apache/apisix/edit/master/docs/zh/latest/discovery.md

![image](https://user-images.githubusercontent.com/2106987/110486681-d4460b80-8127-11eb-96b6-15d9a32ad24b.png)

## Describe the solution you'd like

Those broken links are due to our doc site doesn't support relative reference yet, for example:

![image](https://user-images.githubusercontent.com/2106987/110486810-f770bb00-8127-11eb-8c83-63ccf2a8ce0b.png)

In this file, there have 2 links which are targeted the outside files. Here is the solution to fix this issue:

For those referenced links, please use `https://github.com/apache/apisix/blob/master/docs/en/latest/{FILE_PATH}` instead, e.g: `https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/dns.md`

**Comment by iamayushdas** [comment]
assign this to me @juzhiyuan

**Comment by qier222** [comment]
My last PR only replace links referenced to a markdown file. eureka.lua is not an article, maybe we should place it inside the assets folder.

**Comment by juzhiyuan** [comment]
Could we maintain a file ext list? like `lua,md`.

**Comment by qier222** [comment]
> Could we maintain a file ext list? like `lua,md`.

I can easily do this, but I think place it inside the assets folder is a better option.

**Comment by juzhiyuan** [comment]
🤔 It's a core file for APISIX, that's why we couldn't move it to docs folder 😊

**Comment by qier222** [comment]
> 🤔 It's a core file for APISIX, that's why we couldn't move it to docs folder 😊

If this file is not inside the docs folder, then it will not be copied when execute sync-docs.js. 

![image](https://user-images.githubusercontent.com/68148142/110946712-3007d300-837a-11eb-8fb2-d4d9515300d1.png)

**Comment by juzhiyuan** [comment]
ok, it makes sense to me.
