### ISSUE TITLE
Typo in the title of limit-count plugin

### ISSUE THREAD

**Issue by tokers** [apache/apisix-website#264]
**Actual Behaviour**

The title of limit-count plugin is "limit-connt".

**Expected Behaviour**

The title should be limit-count.

**Steps to reproduce it**

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10428333/111579186-877dc700-87f0-11eb-89d9-e9df7f82b579.png)

**Would you like to work on the issue?**

**Comment by stu01509** [comment]
I will fix it 😃
