### ISSUE TITLE
support jsDelivr to speedup static files

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#266]
Hi, after https://github.com/apache/apisix-website/pull/260 is merged, we have all logos inside our repository, and now when users visit apisix.apache.org , all logos will serve from GitHub, we need to speedup those files.

**Solution**
1. visit https://www.jsdelivr.com/?docs=gh to know what jsDelivr does;
2. update https://github.com/apache/apisix-website/blob/master/website/src/pages/index.js#L123 `src` prop with jsDelivr . All files are under https://github.com/apache/apisix-website/tree/master/website/static/img/showcase this folder.

**Comment by stu01509** [comment]
I would like to try this :)

**Comment by juzhiyuan** [comment]
not hard AFAIK, but it will speedup the website 😄

**Comment by stu01509** [comment]
I think we need to change the static image to https://cdn.jsdelivr.net/gh/apache/apisix-website@master/website/static/img/showcase/163.png right?

**Comment by juzhiyuan** [comment]
ya

**Comment by juzhiyuan** [comment]
that's right

**Comment by juzhiyuan** [comment]
How about doing something like `src={"https://xxx/" + "163.png"}`, no need to update `json` file

**Comment by stu01509** [comment]
Sure, I will do it later

**Comment by stu01509** [comment]
Also, Could I define the global variables to store the `https://cdn.jsdelivr.net/gh/apache/apisix-website@master/`, What do you think?

**Comment by juzhiyuan** [comment]
sure, and you could use docusarus.config.js to do that? would better if possible
