### ISSUE TITLE
make contents' space wirder by reducing sidebar's width

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#268]
**Actual Behaviour**

Hi, we noticed that there have some tables inside our docs and because the content is too long, the scrollbar is shown 😂 Could we reduce the right sidebar's width and give more space to contents?

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/2106987/111965159-65f24780-8b30-11eb-8f79-69735912ddfc.png)

**Comment by stu01509** [comment]
I think maybe we can add the button in the sidebar like `APISIX-Dashboard` to let the user can provider toggle it and expand or collapse the sidebar?

**Comment by juzhiyuan** [comment]
Could you have a try? please search Docusarus if it supports that feature 😊

**Comment by stu01509** [comment]
I found something solution, seems like it can approach.

![image](https://user-images.githubusercontent.com/22230889/112111126-bf20b080-8bee-11eb-9055-fca1bb2536da.png)

![image](https://user-images.githubusercontent.com/22230889/112111153-c8118200-8bee-11eb-9a4b-83e57bb1c217.png)

https://github.com/facebook/docusaurus/pull/3615#issuecomment-726738519
https://deploy-preview-3739--docusaurus-2.netlify.app/classic/docs/

**Comment by juzhiyuan** [comment]
good good
