### ISSUE TITLE
Apache apisix official website part of the Chinese page is displayed in English

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-website#27]
Apache apisix official website part of the Chinese page is displayed in English

Such as, http://apisix.apache.org/zh/contribute/contributor/
![image](https://user-images.githubusercontent.com/3816205/78041859-d7773a00-73a3-11ea-89ae-d7050f805f53.png)

or http://apisix.apache.org/zh/contribute/security/

**Comment by juzhiyuan** [comment]
will be fixed by #47 #46 #45 #44 #35
