### ISSUE TITLE
feat: add a new blog on "Traffic Split in Apache APISIX Ingress Controller"

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#278]
**Actual Behaviour**

We have old blogs in our blog page

**Expected Behaviour**

Newly published blog has to be added on our blog page about "Traffic Split in Apache APISIX Ingress Controller" published by our very own 'Chao Zhang'  

**Steps to reproduce it**

https://github.com/apache/apisix-website/tree/master/website/blog

**Would you like to work on the issue?**

Yes i would like to work on this issue if no one else picks it up

How you can solve it ?
1. Create a file called: 2021-03-27-traffic-split-in-apache-apisix-ingress-controller.md
2. Copy contents from Original File[1] to the new file;
3. File your First PR!

[1] Original File: https://github.com/api7/website/blob/master/_posts/blog/en-US/traffic-split-in-apache-apisix-ingress-controller.md
We are going to publish it here: https://github.com/apache/apisix-website/tree/master/website/blog

![image](https://user-images.githubusercontent.com/40708551/113476523-9ecbde00-9499-11eb-8728-f10690414574.png)

**Comment by juzhiyuan** [comment]
thanks!

**Comment by iamayushdas** [comment]
Anyone haven’t picked this issue , i think i should resolve it right away, what say? @juzhiyuan

**Comment by juzhiyuan** [comment]
That would be great!
