### ISSUE TITLE
When clicking the En button of the current page, the page it jumps to is not reasonable

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-website#28]
When I click the En button of the current page, it jumps to the official website page instead of the English version of the current page.

![image](https://user-images.githubusercontent.com/3816205/78042114-2b821e80-73a4-11ea-9dd5-ff7bb634b29b.png)

After the jump

![image](https://user-images.githubusercontent.com/3816205/78042144-389f0d80-73a4-11ea-81fb-75fe8e697296.png)

**Comment by sshniro** [comment]
Hi, 
I have experienced this. but was thinking this was an isolated event!

**Comment by juzhiyuan** [comment]
The easy way to fix it is just replacing current location code with target code in url, welcome PR!
