### ISSUE TITLE
Improve: the chinese version of website’s homepage

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#280]
**Actual Behaviour**

While switching the website to chinese language,
It’s not fully written in chinese
Like 
Header buttons

**Expected Behaviour**

 Website should be in chinese form at max while changing its language state to chinese.

**Steps to reproduce it**

1. Open website 
2. Then change the language to chinese

**Screenshots of the issue**
![scrnli_05_04_2021_13-41-34](https://user-images.githubusercontent.com/40708551/113554220-9cdb5980-9616-11eb-8ec9-50831fbb45b8.png)

**Would you like to work on the issue?**
This could be a good first issue so, if someone would like to take it , its okay otherwise i will be doing it.

**Comment by juzhiyuan** [comment]
Thanks for this issue! @iamayushdas we could guide more contributors to do this 😊

**Comment by iamayushdas** [comment]
> Thanks for this issue! @iamayushdas we could guide more contributors to do this 😊

Your welcome, yeah sure we should guide other newbies

**Comment by stu01509** [comment]
If anyone needs Chinese translation welcome to ping me 😀

**Comment by juzhiyuan** [comment]
duplicate as #402
