### ISSUE TITLE
page not found for Apisix Docker and Apisix Helm Chart

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#281]
**Actual Behaviour**

![Screenshot (74)](https://user-images.githubusercontent.com/53715187/113585335-b9dd5000-9649-11eb-8aff-07434746de68.png)

**Expected Behaviour**
Page has to  be accessed 

**Steps to reproduce it**
go to docusaurus.config.js
add some codes like https://github.com/apache/apisix-website/blob/master/website/docusaurus.config.js

**Would you like to work on the issue?**
Yes

**Comment by juzhiyuan** [comment]
thanks!
