### ISSUE TITLE
bug: hidableSidebar does not behave correctly

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#288]
**Actual Behaviour**

After I try to hide the sidebar, the page would move and I have to scroll to find where I just read.

Example: http://apisix.incubator.apache.org/docs/apisix/admin-api#service

**Expected Behaviour**

The page would not move, or the first line of the page would not change. And that's how doc of docusauras works so I think it's supported.

Example: https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima

**Steps to reproduce it**

Open a page, scroll down a bit, and hide the sidebar.

**Comment by Yiyiyimu** [comment]
Some other point comparing Docusaurus official doc (which using docusaurus

1. the right sidebar is slightly more right, so there are more space for the middle part, which is crucial to us since we have a lot of table inside.
2. when doing the operation "sidebar hide", the animation is not so smooth and a bit tore apart, while on the official site it's super smooth. It could be reproduced also by the two links presented on the top.

**Comment by Yiyiyimu** [comment]
That PR actually not related to this issue 🤣

**Comment by iamayushdas** [comment]
Its totally okay i guess, the content will get shifted to upward direction as the size of screen get enlarged as we have a big text present in the description. 
it is totally fine that the text shifts to upward while collapsing sidebar 
IMO
@juzhiyuan DO YOU AGREE WITH ME?

**Comment by Yiyiyimu** [comment]
@iamayushdas So is there any benefit to let it shift?

**Comment by juzhiyuan** [comment]
I would prefer keeping it the same line if we could, the sudden jump makes me feel not good..

![image](https://user-images.githubusercontent.com/2106987/116854029-9f3ace80-ac29-11eb-92d0-e67877519f60.png)

![image](https://user-images.githubusercontent.com/2106987/116854037-a366ec00-ac29-11eb-93c5-0a7af696248e.png)

**Comment by 1502shivam-singh** [comment]
@juzhiyuan  @Yiyiyimu  It seems this issue is solved now. Don't see any jerks or snapping no more on my system. 

Least that can be done now is to hide the x-scroll bar when sidebar is out, so the text doesn't block.
If you feel this is good, I will submit a PR for this.

**Comment by Yiyiyimu** [comment]
> @juzhiyuan @Yiyiyimu It seems this issue is solved now. Don't see any jerks or snapping no more on my system.
> 
> Least that can be done now is to hide the x-scroll bar when sidebar is out, so the text doesn't block.
> If you feel this is good, I will submit a PR for this.

Cool! Looking forward to the PR!!
