### ISSUE TITLE
bug: dark mode not fully support homepage

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#291]
An awkward thing is when text is not in black (for example some dark grey), dark mode seems could not get its opponent color...

![image](https://user-images.githubusercontent.com/34589752/114053428-873d8c80-98c1-11eb-820c-f8faf367036d.png)

One possible solution to deal with this situation is like the tagline of https://docusaurus.io/, to make it stale and not get affected by the dark mode.

**Light mode**
![image](https://user-images.githubusercontent.com/34589752/114054558-8ce7a200-98c2-11eb-89ea-3fd568687940.png)

**Dark mode**
![image](https://user-images.githubusercontent.com/34589752/114054583-92dd8300-98c2-11eb-8b91-9e1e5885537d.png)

I tried to find the method to make it stale but failed 😿 crying again for not familiar with frontend

**Comment by iamayushdas** [comment]
don't worry , let me look into this :smiley:

**Comment by iamayushdas** [comment]
@juzhiyuan @nic-chen 
Have a look to this , is it cool or not ? 
![scrnli_09_04_2021_11-15-56](https://user-images.githubusercontent.com/40708551/114134317-29db2700-9925-11eb-8e1f-aa84c25bee6d.png)

as compared to

![scrnli_09_04_2021_11-19-06](https://user-images.githubusercontent.com/40708551/114134466-6c046880-9925-11eb-8a0c-43405f3995ec.png)

**Comment by iamayushdas** [comment]
@Yiyiyimu which suits you most?

**Comment by Yiyiyimu** [comment]
@iamayushdas So cool! Just two suggestions
1. it might be better to also darken the `description` part. We could provide that architecture graph in both light and dark mode. Need help from @juzhiyuan.
2. Some of the text may get too dark gray in the dark mode, so the readability is not that good

**Comment by nic-chen** [comment]
> @iamayushdas So cool! Just two suggestions
> 
> 1. it might be better to also darken the `description` part. We could provide that architecture graph in both light and dark mode. Need help from @juzhiyuan.
> 2. Some of the text may get too dark gray in the dark mode, so the readability is not that good

I have the same view.

**Comment by iamayushdas** [comment]
> > @iamayushdas So cool! Just two suggestions
> 
> > 
> 
> > 1. it might be better to also darken the `description` part. We could provide that architecture graph in both light and dark mode. Need help from @juzhiyuan.
> 
> > 2. Some of the text may get too dark gray in the dark mode, so the readability is not that good
> 
> 
> 
> I have the same view.
> 
> 

Okay working on it then

**Comment by iamayushdas** [comment]
Are you okay with that Grayish title?

**Comment by iamayushdas** [comment]
![scrnli_09_04_2021_22-26-20](https://user-images.githubusercontent.com/40708551/114214991-aea85e00-9982-11eb-8440-b2ba75d57af9.png)

@Yiyiyimu @nic-chen @juzhiyuan how about this?

**Comment by Yiyiyimu** [comment]
@iamayushdas Nice! For me, I have some other suggestions. Just take it or leave it with your preferences 😁 
1. It might be a good idea to propose a PR, so we could have a more instinctive view of the actual website rather than screenshots
2. For the description part, IMO, we could have a darker background with lighter(whitish) text to be compatible with other parts of the whole website. And still, the background of this part better different from other ones.
3. Grayish title is absolutely great, it's the main part of the dark mode. But the problem is it seems too dark right now so the contract between text and background is not clear enough. A example from DuckDuckGo
![image](https://user-images.githubusercontent.com/34589752/114256464-fadbb880-99eb-11eb-9e78-46ef8b056723.png)
