### ISSUE TITLE
docs: for helm chart and docker ,tell users where they are

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#298]
users may get confusing because they couldn't know which project they are reading so We could add the Project name in the sidebar.

related issue: #230

**Comment by KishaniKandasamy** [comment]
#230

**Comment by juzhiyuan** [comment]
Thanks! Kishani.

**Comment by KishaniKandasamy** [comment]
> Thanks! Kishani.

👍🏻👍🏻
