### ISSUE TITLE
fix: made dark mode compatible APISIX architecture image 

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#301]
**Actual Behaviour**

Website consisting of apisix architecture is not flexible wiith dark mode

**Expected Behaviour**

 Image should be flexible with different kind of themes.

**Steps to reproduce it**

 open webiste and scroll to description section there you will see the architecture image

**Screenshots of the issue**

![scrnli_11_04_2021_09-51-06](https://user-images.githubusercontent.com/40708551/114303119-0c0aef00-9aea-11eb-876f-ee247d52b095.png)

**Would you like to work on the issue?**

Yes i have just created that image again which will be flexible
here it is 
![apisix](https://user-images.githubusercontent.com/40708551/114303150-44aac880-9aea-11eb-8479-96fb3f9d0ba9.png)

[APISIX GDrive image](https://drive.google.com/file/d/1aLLdo5NA9I8hUJnqEV7oqGbqwwtmDt9C/view?usp=sharing)

**Comment by iamayushdas** [comment]
@Yiyiyimu @juzhiyuan @nic-chen

**Comment by juzhiyuan** [comment]
Thanks, buddy! It LGTM

**Comment by iamayushdas** [comment]
> Thanks, buddy! It LGTM

Your welcome Sir!

**Comment by Yiyiyimu** [comment]
Close since fixed
