### ISSUE TITLE
feat: add Chinese support for the website

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#302]
Currently, we only got Chinese support for Navbar. A good start could be translating the front page.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34589752/114332315-9306a880-9b78-11eb-9a9a-4b8ce1e9fdfc.gif)

**Comment by iamayushdas** [comment]
Shuyang sir! this is a duplicate issue, i already raised it see #280

**Comment by Yiyiyimu** [comment]
> Shuyang sir! this is a duplicate issue, i already raised it see #280

Thanks for reminding!!
