### ISSUE TITLE
update the architecture diagram 

### ISSUE THREAD

**Issue by membphis** [apache/apisix-website#307]
current:

![image](https://user-images.githubusercontent.com/6814606/114640813-721e8e80-9d03-11eb-860a-40be88f15779.png)

change to:

![image](https://user-images.githubusercontent.com/6814606/114640838-7ea2e700-9d03-11eb-8296-ce444111d440.png)

**Comment by iamayushdas** [comment]
okay then i have to again create the darkmode flexi format and  will push it today only. 

> current:
> 
> ![image](https://user-images.githubusercontent.com/6814606/114640813-721e8e80-9d03-11eb-860a-40be88f15779.png)
> 
> change to: 
> 
> ![image](https://user-images.githubusercontent.com/6814606/114640838-7ea2e700-9d03-11eb-8296-ce444111d440.png)

The image you have suggested to change is of solid background. we could do either from the two things below:
1. we have to remove the alpha from the image
2. we have to recreate it(recommended for sake of pointing arrows)
  
@membphis @juzhiyuan which option to opt?

**Comment by juzhiyuan** [comment]
Maybe have a try here:

https://www.remove.bg/

**Comment by iamayushdas** [comment]
> Maybe have a try here:
> 
> 
> 
> https://www.remove.bg/

That site disrupts the image. Don't worry i have created a new one

**Comment by juzhiyuan** [comment]
ok

**Comment by iamayushdas** [comment]
@

> current:
> 
> ![image](https://user-images.githubusercontent.com/6814606/114640813-721e8e80-9d03-11eb-860a-40be88f15779.png)
> 
> change to:
> 
> ![image](https://user-images.githubusercontent.com/6814606/114640838-7ea2e700-9d03-11eb-8296-ce444111d440.png)

you have suggested to change in apisix here!
