### ISSUE TITLE
broken link in Apisix FAQ

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#310]
The link for benchmark(https://github.com/apache/apisix/blob/master/benchmark.md) in FAQ is broken.

![Capture PNG1](https://user-images.githubusercontent.com/53715187/114747176-2ead3a00-9d6e-11eb-8a49-fade4132d054.PNG)

some others links are also broken. 
![9](https://user-images.githubusercontent.com/53715187/114758018-23600b80-9d7a-11eb-9dc0-464f78b8cda6.PNG)

![Screenshot (115)](https://user-images.githubusercontent.com/53715187/114757732-d54b0800-9d79-11eb-9ed4-542964748f33.png)

**Comment by juzhiyuan** [comment]
thanks for your report!
