### ISSUE TITLE
docs: design of apisix ingress-controller  is not included in the sidebar

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#323]
**Actual Behaviour**

https://apisix.apache.org/docs/ingress-controller/design
![Screenshot (151)](https://user-images.githubusercontent.com/53715187/116287928-96bc4100-a7ae-11eb-8bb1-76f5bcf8ca9b.png)

**Comment by KishaniKandasamy** [comment]
#321

**Comment by tokers** [comment]
@KishaniKandasamy Thanks for your report!
