### ISSUE TITLE
docs: link is broken

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#325]
**Actual Behaviour**

 There are some broken links in **ingress** docs.**_What about fixing these issues for now  or we could wait until  Markdown Link Checker is back??_**

Would you like to work on the issue?
**yes i would like to work on this issue**

![Inked9_LI](https://user-images.githubusercontent.com/53715187/116507506-029cc780-a8dd-11eb-98d6-8ad47dba8b95.jpg)
![Inked18_LI](https://user-images.githubusercontent.com/53715187/116507510-04ff2180-a8dd-11eb-87bd-a364ccaafba4.jpg)
![27](https://user-images.githubusercontent.com/53715187/116506944-f2381d00-a8db-11eb-9c4c-f1abd8219815.JPG)
![36](https://user-images.githubusercontent.com/53715187/116506947-f2d0b380-a8db-11eb-9bdd-425200601ad1.JPG)
![45](https://user-images.githubusercontent.com/53715187/116506948-f3694a00-a8db-11eb-8689-d8374cef0f09.JPG)
![54](https://user-images.githubusercontent.com/53715187/116506949-f401e080-a8db-11eb-97eb-96a600ed4e71.JPG)

**_What about fixing these issues for now  or we could wait until  Markdown Link Checker is back??_**

**Comment by KishaniKandasamy** [comment]
@juzhiyuan  @tokers

**Comment by tokers** [comment]
We can fix it now.
