### ISSUE TITLE
docs: many broken links our residing in website

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#326]
**Actual Behaviour**

Many of the links are broken

**Expected Behaviour**

All the links should be working fine

**Steps to reproduce it**

Check ingress and helm pages

**Screenshots of the issue**

 
![Screenshot from 2021-04-30 22-22-14](https://user-images.githubusercontent.com/40708551/116728225-45f15600-aa03-11eb-914d-bc872d281700.png)
![Screenshot from 2021-04-30 22-24-18](https://user-images.githubusercontent.com/40708551/116728234-4853b000-aa03-11eb-92b7-09c5064e5f2e.png)

**Would you like to work on the issue?**

yes i would like to work on this issue

**Comment by iamayushdas** [comment]
also should we remove the kubernetes link - 	https://kubernetes-sigs.github.io/service-apis/ ?
if yes please let me know @juzhiyuan

**Comment by KishaniKandasamy** [comment]
Hi @iamayushdas ,
I am currently working on this issue #325 
I think you might not have noticed [it](https://github.com/apache/apisix-website/issues/325) ;)

**Comment by tokers** [comment]
> also should we remove the kubernetes link - 	https://kubernetes-sigs.github.io/service-apis/ ?
> 
> if yes please let me know @juzhiyuan

I'd like to know the reason that you think this link should be removed.

**Comment by iamayushdas** [comment]
Because this link doesn't exist..i have tried to find its exact url but no clues

**Comment by iamayushdas** [comment]
> Hi @iamayushdas ,
> 
> I am currently working on this issue #325 
> 
> I think you might not have noticed [it](https://github.com/apache/apisix-website/issues/325) ;)

My issue is majorly regarding helm and kubernetes but you were only working on ingress related error

**Comment by tokers** [comment]
> Because this link doesn't exist..i have tried to find its exact url but no clues

Oops, it was migrated to this site: https://gateway-api.sigs.k8s.io/

**Comment by iamayushdas** [comment]
@xdshivani would you like to work in this issue?
