### ISSUE TITLE
[Fe] dark mode enhancement in download page

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#329]
**Actual Behaviour**
In dark mode
Dialogue appearing after clicking Download button in download page does not follow dark mode

**Expected Behaviour**
Dialogue box should also be following dark mode

**Steps to reproduce it**

- Goto apisix.apache.org -> click downloads -> click download button 

**Screenshots of the issue**

![scrnli_04_05_2021_14-42-52](https://user-images.githubusercontent.com/40708551/116983812-2d758a00-ace8-11eb-9781-ee17656c3e71.png)

**Would you like to work on the issue?**

yes i would like to work in this issue,  but as this could be the good first issue , i would like new committers to give a PR :smiley:

**Comment by juzhiyuan** [comment]
sure
