### ISSUE TITLE
Update Release Guide

### ISSUE THREAD

**Issue by agile6v** [apache/apisix-website#33]
Hi @juzhiyuan 

Please help to add the following information to the content/contribute/release/index.zh.md and content/contribute/release/index.en.md file.

Thanks.    

<h3 class="subtitle">统计投票结果</h3>
    <p><a href="https://lists.apache.org/thread.html/r8c6e14ea1a0c79b5dfb1dba0e1b6bc919a4797a0c4664f8add3b045c%40%3Cdev.apisix.apache.org%3E">点击此处查看参考邮件</a> 发起投票邮件后需要等待72小时，然后统计投票结果并发送一封 result 邮件到 dev@apisix.apache.org。</p>
    <h3 class="subtitle">再次发起投票邮件</h3>
    <p><a href="http://mail-archives.apache.org/mod_mbox/incubator-general/202004.mbox/%3cCABZgMXH7e-CfxXBr5fuPsEAsfMXU4jGs4L7EM2qz+zTcHP=u1w@mail.gmail.com%3e">点击此处查看参考邮件</a> 在 general@incubator.apache.org 发起投票邮件，同时需要将在 dev@apisix.apache.org 邮件列表中的统计结果附加到此封邮件，主要参考内容：邮件发送人（apache 邮箱）、邮件标题、邮件正文（主要是修改版本号和链接地址）。</p>
    <h3 class="subtitle">再次统计投票结果</h3>
    <p><a href="http://mail-archives.apache.org/mod_mbox/incubator-general/202004.mbox/%3cCABZgMXFAL247-9u4ehaBxrEzHKjYkzhH2iZuiU2jdTx7zG4bzw@mail.gmail.com%3e">点击此处查看参考邮件</a> 发起投票邮件后需要等待72小时，然后统计投票结果并发送一封 result 邮件到 general@incubator.apache.org。</p>
    <h3 class="subtitle">发 announce 邮件</h3>
    <p><a href="https://lists.apache.org/thread.html/r67093ed9a5fbe106dc5066c283f225544f5ae14248df061019d1062e%40%3Cgeneral.incubator.apache.org%3E">点击此处查看参考邮件</a> 在 dev@apisix.apache.org 和 general@incubator.apache.org 两个邮件列表发起 announce 邮件</p>
    <h3 class="subtitle">移动安装包到 release 目录下</h3>
    <p>将RC版本的安装包修改为正式版以后移动到<a href="https://dist.apache.org/repos/dist/release/incubator/apisix/"> 此地址</a></p>
    <h3 class="subtitle">更新下载信息</h3>
    <p> 更新<a href="http://apisix.apache.org/downloads/"> 此地址 </a>的下载信息， 源码在 https://github.com/apache/incubator-apisix-website</p>

**Comment by moonming** [comment]
@juzhiyuan any update?

**Comment by juzhiyuan** [comment]
ok, I will do it soon!

**Comment by juzhiyuan** [comment]
Just updated, but have Chinese version only currently.
