### ISSUE TITLE
docs: add Last updated on ,  by to docs

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-website#330]
**Actual Behaviour**

 Except https://apisix.apache.org/docs/general/  docs, Other projects lack  details about when docs are updated by whom. 

**Expected Behaviour**
 Docs contains when docs are updated by whom. 
Something like  apisix-website/website/docs/general/
![ki](https://user-images.githubusercontent.com/53715187/116991732-9feb6780-acf2-11eb-93f7-3059a39054bb.JPG)

**Steps to reproduce it**
 I think we could add showLastUpdateAuthor and  showLastUpdateTime to docusurus.config.json for other docs.

 **Would you like to work on the issue?**
Yes.I would like to work on it

**Comment by juzhiyuan** [comment]
ok! But those docs are pulling from origin repos, not sure if it's working without Git history 🤔 please have a try!

**Comment by KishaniKandasamy** [comment]
> ok! But those docs are pulling from origin repos, not sure if it's working without Git history 🤔 please have a try!

Okay  👍  I will try
