### ISSUE TITLE
[Fe] speed up loading using HTTP/2 in place of HTTP/1.1

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#335]
**Actual Behaviour**

 Resources of our website currently loads slower 
 Reason: We currently use HTTP/1.1 ,

**Expected Behaviour**

 we should be using  HTTP/2 to make resources loads faster 

**Steps to reproduce it**

**Would you like to work on the issue?**

 Not, totally sure about this, need to no more how its works and then i will be working on this
 If someone could guide me, i will be thankful to him/her

**Comment by juzhiyuan** [comment]
No, the website is based on Apache's infrastructure, not sure if it supports HTTP2. BTW, HTTP2 is no hurry now, maybe you could resolve other issues reported from Lighthouse?

**Comment by iamayushdas** [comment]
Yep, sure
