### ISSUE TITLE
feature request: increase main contents max width

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#344]
**Actual Behaviour**

After collapsing sidebars, there are still quite a lot of blank spaces on both sides of the page, so the table in the doc (like [this](https://apisix.apache.org/docs/apisix/admin-api#route)) actually presents in a kind of awkward way (one sentence being broken into several lines). So I think it might be better if we could also increase main contents' max width, so the presence of table could be better

![image](https://user-images.githubusercontent.com/34589752/118174953-78d11c00-b3fd-11eb-898b-fa4d007c3cc3.png)

**Comment by 1502shivam-singh** [comment]
Hey @Yiyiyimu , could you provide a link to where this table is, just so that people can find this section easily. 
And, is this problem with every table in the docs or for just this one ?

**Comment by Yiyiyimu** [comment]
@1502shivam-singh Thanks for the remind! The link to the screenshot is https://apisix.apache.org/docs/apisix/admin-api#route, and yes, that's the problem for all over the documentations.

**Comment by iamayushdas** [comment]
Working on it

**Comment by iamayushdas** [comment]
@Yiyiyimu have a look to this and compare
https://apisix-website-sidebarfix.netlify.app/docs/apisix/admin-api

Earlier
![scrnli_17_05_2021_15-00-02](https://user-images.githubusercontent.com/40708551/118466644-ac26ea00-b720-11eb-9c3d-c4ece75e6755.png)

now:
![scrnli_17_05_2021_14-59-51](https://user-images.githubusercontent.com/40708551/118466671-b34df800-b720-11eb-93c5-49a5e2690088.png)


also while decreasing right side space , not getting the desired result, still trying for right side

**Comment by 1502shivam-singh** [comment]
> now:
> ![scrnli_17_05_2021_14-59-51](https://user-images.githubusercontent.com/40708551/118466671-b34df800-b720-11eb-93c5-49a5e2690088.png)
> 
> also while decreasing right side space , not getting the desired result, still trying for right side

Hey @iamayushdas. I guess what @Yiyiyimu is talking about is increasing the overall width of the main content on this page and elsewhere where there are tables, as in using a small part of the unused space on the right (or left, keeping proportions) to increase the overall width of the table for not so congested text in the table fields.

My recommendation would be to try to use some space from the right side (or left), to increase the width of the table and relieve the congestion when sidebar is closed.

**Comment by 1502shivam-singh** [comment]
Also, something I noticed @Yiyiyimu, the margin from the left in your provided shot, is way more than on my system (Just thinking, maybe I have a small screen 😅). Have you zoomed out in your browser ? maybe check that. 

> ![image](https://user-images.githubusercontent.com/34589752/118174953-78d11c00-b3fd-11eb-898b-fa4d007c3cc3.png)

**Comment by iamayushdas** [comment]
But their is something bad bad, that it has same configuration as docusaurus but,
Many of its configs are not properly working in our website, like collapsing sidebar is not smooth, page slides up a bit while toggling sidebar.

**Comment by 1502shivam-singh** [comment]
> But their is something bad bad, that it has same configuration as docusaurus but,
> Many of its configs are not properly working in our website, like collapsing sidebar is not smooth, page slides up a bit while toggling sidebar.

Yes, I saw another issue related to scroll snapping. Try solving this one first, we will look into those later maybe.

**Comment by iamayushdas** [comment]
Yes

**Comment by Yiyiyimu** [comment]
> Also, something I noticed @Yiyiyimu, the margin from the left in your provided shot, is way more than on my system (Just thinking, maybe I have a small screen 😅). Have you zoomed out in your browser? maybe check that.

No zoom out when make that screenshot. Maybe I indeed have a larger screen 🤣

**Comment by 1502shivam-singh** [comment]
> No zoom out when make that screenshot. Maybe I indeed have a larger screen 🤣

Damn 😎

On my laptop

![image](https://user-images.githubusercontent.com/57267960/118548140-9395ee80-b777-11eb-89b6-8e4991de27f1.png)

**Comment by Yiyiyimu** [comment]
> Damn 😎
> On my laptop

Lol envy u 🤣 

Yes there would be less blank space on the smaller screen, but the table is still lack of readability. 
It seems docusaurus would make the last column takes larger space (I guess it takes as granted that the last column would be the description). So maybe, I say maybe we could move the description to the last column. Maybe it could get better looking.

I'll appreciate it if you could give it a test on the order switch~

**Comment by 1502shivam-singh** [comment]
> Yes there would be less blank space on the smaller screen, but the table is still lack of readability.

Yup true.

> It seems docusaurus would make the last column takes larger space (I guess it takes as granted that the last column would be the description). So maybe, I say maybe we could move the description to the last column. Maybe it could get better looking.
> I'll appreciate it if you could give it a test on the order switch~

Ayush is working on this I guess. @iamayushdas maybe try this.

**Comment by iamayushdas** [comment]
> > Yes there would be less blank space on the smaller screen, but the table is still lack of readability.
> 
> 
> 
> Yup true.
> 
> 
> 
> > It seems docusaurus would make the last column takes larger space (I guess it takes as granted that the last column would be the description). So maybe, I say maybe we could move the description to the last column. Maybe it could get better looking.
> 
> > I'll appreciate it if you could give it a test on the order switch~
> 
> 
> 
> Ayush is working on this I guess. @iamayushdas maybe try this. 
> 
> 

Sure @1502shivam-singh

**Comment by 1502shivam-singh** [comment]
> Many of its configs are not properly working in our website, like collapsing sidebar is not smooth, page slides up a bit while toggling sidebar.

Guys I think sidebar movement is now smooth too, after setting max-width width attrib. to the doc-container. Recommend you all to check it out to confirm.

**Comment by Yiyiyimu** [comment]
Fixed confirm. Issue closed.
Thanks again @1502shivam-singh!

**Comment by 1502shivam-singh** [comment]
I guess I commented in the wrong place, my apologies 😅. Wasn't this issue related to table widths and all. 
Are you fine with them now , as you closed this?

**Comment by Yiyiyimu** [comment]
@1502shivam-singh Sorry my bad 🤣 Thanks for remind
