### ISSUE TITLE
use navbar_version instead of sidebar_version

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#352]
So when users collapse the sidebar, they could still change doc versions. (And for me navbar version looks a bit nicer 🤣 

**Actual Behaviour**

![image](https://user-images.githubusercontent.com/34589752/119389431-a047a480-bc99-11eb-8d2a-47c1b9e523d7.png)

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/34589752/119389471-ab023980-bc99-11eb-979c-20fbbbe19ecc.png)
![image](https://user-images.githubusercontent.com/34589752/119389480-b05f8400-bc99-11eb-8cc9-387db80576cf.png)

**Comment by juzhiyuan** [comment]
Just to make sure, the navbar version selector is globally? If we visit the homepage, will it appear?

**Comment by Yiyiyimu** [comment]
> Just to make sure, the navbar version selector is globally? If we visit the homepage, will it appear?

I think yes, see https://docusaurus.io/ and https://chaos-mesh.org/. But I'm not sure if it's configuratble

**Comment by juzhiyuan** [comment]
We have multiple docs instance, not sure if it's configurable 🤣 What do you think? @qier222

**Comment by Yiyiyimu** [comment]
> We have multiple docs instance

My bad I didn't realize this problem 🤣

**Comment by 1502shivam-singh** [comment]
Chiming in, `Navbar_version` on apisix-website would make sense, when it shows only when we are on a documentation page so we can traverse between versions, and hide it when we out of the docs and let the navbar stay as it's like on the current design.

I feel doing this is possible, but hacky 😅

**Comment by iamayushdas** [comment]
@Yiyiyimu I have personally worked on it before release, version selection in sidebar is far better option than in navbar, @qier222 has intelligently done it rightly, 
adding that selector in navbar will ruin the look and feel of navbar, by making it crowded I guess, 

do you agree Shuyang sir?

**Comment by Yiyiyimu** [comment]
> adding that selector in navbar will ruin the look and feel of navbar, by making it crowded I guess

Although I do not agree with this but it's more about personal favor, so close this issue since it's trivial.
