### ISSUE TITLE
bug: Official website Chinese doc showing English 

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix-website#354]
All of them, e.g. https://apisix.apache.org/zh/docs/apisix/getting-started/

**Comment by Yiyiyimu** [comment]
ping @juzhiyuan it seems broken 😿

**Comment by juzhiyuan** [comment]
Wired, let me have a check

**Comment by juzhiyuan** [comment]
cc @qier222 to have a check. Maybe related to versioned docs JS script?
