### ISSUE TITLE
Bug: broken links 

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#358]
**Actual Behaviour**

Many links residing in apisix website are broken
some of the images are broken in dashboard docs only in `v2.5`

**Expected Behaviour**

 All the images should be active in dashboard docs

**Steps to reproduce it**

 while reading docs in `v2..5` of apisix-dashboard

**Checklist**

- [ ] `apisix-dashboard v2.5` image links
- [ ] https://www.dataoke.com/
- [ ] https://www.sinovatech.com/
- [ ] http://www.tangdou.com/
- [ ] https://github.com/apache/apisix/blob/master/t/plugin/proxy-rewrite.lua
- [ ] https://apisix.apache.org/conf/config.yaml
- [ ] https://apisix.apache.org/docs/how-to-build.md
- [ ] https://raw.githubusercontent.com/apache/apisix/master/docs/assets/images/dashboard.png
- [ ] https://github.com/apache/apisix/blob/master/CODE_STYLE
- [ ] https://github.com/apache/apisix/blob/master/CHANGELOG
- [ ] https://apisix.apache.org/assets/other/json/apisix-grafana-dashboard.json
- [ ] https://apisix.apache.org/apisix/discovery/eureka.lua
- [ ] https://apisix.apache.org/docs/apisix/https.md

**Screenshots of the issue**

![Screenshot from 2021-05-30 22-20-12](https://user-images.githubusercontent.com/40708551/120112881-6b55b900-c195-11eb-80d0-7d38a4f985c1.png)

**Would you like to work on the issue?**

Yes I can work with this issue but want  to attract more open source contributors to our org, else i will be doing it :smile: 
I would request only new contributors to look into it
New contributors can ping me for help
Thank you

**Comment by iamayushdas** [comment]
Could you please add - `first-timers-only` label to this issue? @Yiyiyimu 
This will make our reach to more people

Source- https://www.firsttimersonly.com

**Comment by Neilblaze** [comment]
@iamayushdas Assign me, please.

Also, a few of the links mentioned above are not invalid. While I was running the apisix-website on my local, I noticed that the docs @[v2.5](https://apisix.apache.org/docs/dashboard/2.5/USER_GUIDE) isn't opening & showing error dialog. Can you please let me know how can I access that? 

I'm also uncertain if docusauras use [this](https://github.com/Neilblaze/apisix-dashboard/blob/release/2.5/docs/en/latest/USER_GUIDE.md) to build the blogs?

**Comment by iamayushdas** [comment]
Go ahead @Neilblaze

**Comment by Neilblaze** [comment]
@juzhiyuan can you please let me know how to resolve this?


> Also, a few of the links mentioned above are not invalid. While I was running the apisix-website on my local, I noticed that the docs @[v2.5](https://apisix.apache.org/docs/dashboard/2.5/USER_GUIDE) aren't opening & showing an error dialog. Can you please let me know how can I access that?
> 
> I'm also uncertain if docusauras use [this](https://github.com/Neilblaze/apisix-dashboard/blob/release/2.5/docs/en/latest/USER_GUIDE.md) to build the blogs?

**Comment by iamayushdas** [comment]
Can you send your env info, also have you followed the documentation to run and synchronise docs for the documentation website?

**Comment by Neilblaze** [comment]
> Can you send your env info, also have you followed the documentation to run and synchronise docs for the documentation website?

Yeah sure,

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics           
    Memory: 838.70 MB / 7.37 GB
  Binaries:
    Node: 14.15.3 - D:\Programs\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - D:\Programs\nodejs\npm.CMD
  Managers:
    pip3: 20.2.3 - D:\python_3.9.4\Python\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.29.2. - /cmd/git
  IDEs:
    VSCode: 1.57.0 - D:\Programs\Microsoft VS Code\bin\code.CMD    
  Languages:
    Bash: 4.4.23 - D:\Programs\Git\usr\bin\bash.EXE
    Java: javac 16 - /d/java/jdk-16/bin/javac
    Perl: 5.32.0 - D:\Programs\Git\usr\bin\perl.EXE
    Python: 3.9.4 - /d/python_3.9.4/Python/Python39/python
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1
```

Yes, I've read the docs, but haven't found any specific file(.md) for synchronizing docs for the documentation website. That's exactly where I'm stuck atm.

**Comment by iamayushdas** [comment]
okay let me guide you

have you forked all the repository inside the apisix-website? eg: apisix, dashboard, ingress-controller etc

there are two steps involved 
1. synchronise all docs - check the github workflow directory for more details about how our documentation site is deployed
    - fork and clone the apisix-website
    - cd apisix-website
    - node sync-docs.js
    next
    - cd website
    - yarn && yarn start
    - you will now be able to see all the docs from docs-dropdown,
    now
    - search the broken links i have listed above you will see those, 
    
2. fork the particular repo where the broken link found and fix that link
ping me back when you stuck, welcome to Apache APISIX .

i would like to invite you to join our slack channel. 
[Slack invite](https://join.slack.com/t/the-asf/shared_invite/zt-nggtva4i-hDCsW1S35MuZ2g_2DgVDGg)
