### ISSUE TITLE
[DISCUSS]: Too many 429 http codes exists in website

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#359]
Should we work to handle these repetitive 429 errors?
 
Digging to this issue deeply, i found its all because of `raw.githubusercontent.com` cdn 

![Screenshot from 2021-05-30 22-28-32](https://user-images.githubusercontent.com/40708551/120113490-4e6eb500-c198-11eb-808d-53967fd1b3b6.png)

**Comment by Yiyiyimu** [comment]
If you are using https://github.com/tcort/markdown-link-check#api, you could refer to how to use `retryOn429`.

**Comment by iamayushdas** [comment]
Okay thanks 😊
