### ISSUE TITLE
remove the useless top button on the sidebar

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#360]
Currently in doc for each part, there would be button linking to itself. For example for apisix, there would be an `Apache APISIX` on the top.
![image](https://user-images.githubusercontent.com/34589752/120395227-a6c1c600-c302-11eb-89f5-3d60d2008cbe.png)

If users click it, it would direct them to the front page of the same section, so I think we don't need it. 
If we do need it, it might be a good idea to change its outlooking from others so people won't expect there is some kind of overview of apisix after clicking this button.

**Comment by 1502shivam-singh** [comment]
As far as I can remember this was the concerning issue for addition of titles #230 
But you are right, need to change their style, for a hierarchy and proper contrast.

**Comment by Yiyiyimu** [comment]
@1502shivam-singh Thank you for the information! 

Considering the need to show where we are, maybe we could change the field `Docs` in navbar to where we are after one option is chosen, keeps the drop-down arrow so people still know they could switch different docs there
![image](https://user-images.githubusercontent.com/34589752/120545516-c1587580-c3bc-11eb-94aa-9f47c8717061.png)

**Comment by iamayushdas** [comment]
> @1502shivam-singh Thank you for the information!
> 
> Considering the need to show where we are, maybe we could change the field `Docs` in navbar to where we are after one option is chosen, keeps the drop-down arrow so people still know they could switch different docs there
> ![image](https://user-images.githubusercontent.com/34589752/120545516-c1587580-c3bc-11eb-94aa-9f47c8717061.png)

i have achieved your desired idea of changing dropdown title according to page

**Comment by iamayushdas** [comment]
@Yiyiyimu check this link is this what you wanted?
https://apisix-website-navigation.netlify.app/
![scrnli_04_06_2021_22-40-22](https://user-images.githubusercontent.com/40708551/120838840-e64c1480-c585-11eb-9dd1-28f53b6a4e23.png)
