### ISSUE TITLE
implementing uniform doc page `id` for all documentation

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#363]
**Actual Behaviour**

The page id is not uniform for any of the documentations present in website

**Expected Behaviour**

There should be a uniformity in id for all docs of our sub projects.

1. you can see here in screenshots that id is random for every page
2. having uniform id's are very useful for developers to play with the DOM and implementing new features

**Screenshots of the issue**

![Screenshot from 2021-06-11 12-27-12](https://user-images.githubusercontent.com/40708551/121644247-6a375c80-cab0-11eb-9212-8ed00415f732.png)
![Screenshot from 2021-06-11 12-26-29](https://user-images.githubusercontent.com/40708551/121644255-6c99b680-cab0-11eb-8ce5-bba2d21189a7.png)

**Proposed solution**
Making uniform subheadings to every documentation.

**Would you like to work on the issue?**

Yes i would like to work on it

@juzhiyuan @Yiyiyimu please share your opinion

**Comment by juzhiyuan** [comment]
Not sure exactly what you mean 😳😳 Could you please describe more clearly?

**Comment by iamayushdas** [comment]
I have used subheading id as get selector to Manipulate DOM in naming the doc dropdown

But newly added commit in "apisix helm chart" has changed the subheading and therefore id is also changed

**Comment by iamayushdas** [comment]
Go to:
1. Apisix website
2. Choose apisix helm chart from doc dropdown
You will see that docs is no longer renamed to what it was supposed to be.
@juzhiyuan

**Comment by juzhiyuan** [comment]
Oh yes, I see what happens.

**Comment by juzhiyuan** [comment]
Just do it

**Comment by iamayushdas** [comment]
After new features from V2 i have got a way to fix this, I am fixing this please reopen it, @juzhiyuan @Yiyiyimu

**Comment by spacewander** [comment]
@iamayushdas 
First of all, you should discuss this in the mail list `dev@apisix.apache.org` before sending a bunch of PRs. It seems only a few people know this purpose.

Secondly, please modify the doc in a repo first, and evaluate the effect. Don't change a lot of things. Change it step by step.

Thirdly, it is not a good idea to put a visible mark on an obvious place. I just spend some time on this issue and get an idea:

Since the doc is pulled from other repo before building it on the website, we can introduce a preprocessor that converts the invisible mark to the mark that can be recognized by the render.

I am not sure if it works but at least there is way to achieve the goal with a better solution.

**Comment by juzhiyuan** [comment]
Agree with @spacewander, please have 1 repo test, or your bunch of PRs will confuse people who don't know this case :)

**Comment by iamayushdas** [comment]
okay we could first go with apisix-dashboard @juzhiyuan

**Comment by iamayushdas** [comment]
> @iamayushdas
> First of all, you should discuss this in the mail list `dev@apisix.apache.org` before sending a bunch of PRs. It seems only a few people know this purpose.
> 
> Secondly, please modify the doc in a repo first, and evaluate the effect. Don't change a lot of things. Change it step by step.
> 
> Thirdly, it is not a good idea to put a visible mark on an obvious place. I just spend some time on this issue and get an idea:
> 
> Since the doc is pulled from other repo before building it on the website, we can introduce a preprocessor that converts the invisible mark to the mark that can be recognized by the render.
> 
> I am not sure if it works but at least there is way to achieve the goal with a better solution.

I understood sir, thank you for making me understand

**Comment by juzhiyuan** [comment]
> Thirdly, it is not a good idea to put a visible mark on an obvious place. I just spend some time on this issue and get an idea:

As for this, because I haven't experienced this case, then it's ok for me to do this (is Docusarus using this? @iamayushdas) Waiting for more suggestions :) 

cc @liuxiran @bzp2010 @lilien1010 @tokers @Yiyiyimu

**Comment by iamayushdas** [comment]
cc @liuxiran @bzp2010 @lilien1010 @tokers @Yiyiyimu
yes docusaurus is using this now on @juzhiyuan 

Docusaurus has opted this way for adding id's to be more precise. they have changed the md style in such a way that we can add precise id without harming our website
**reference md file** - https://github.com/facebook/docusaurus/blob/master/website/docs/api/plugins/plugin-content-blog.md

screenshot: 
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/40708551/123247795-df6d4d80-d504-11eb-9c1f-dbef20dc2225.png">



**website created from above md file**: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog

screenshot: 
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog
<img width="1320" alt="Screenshot 2021-06-24 at 3 55 22 PM" src="https://user-images.githubusercontent.com/40708551/123247579-aaf99180-d504-11eb-8b1f-ab05463c93a1.png">

**Comment by spacewander** [comment]
Are we discussing the "invisible mark way"? We should use a better way to solve the issue. A visible scar is unacceptable.

**Comment by iamayushdas** [comment]
If we change the subtitle with the name of sub-project then, then that name will automatically become the id 

For example- if i name the sub title 

**APISIX-dashboard** 

This will automatically attach an id 
to the subtitle 

**apisix-dashboard**


Also i am discussing about the invisible mark manner in docusaurus mailing list.
@spacewander

**Comment by iamayushdas** [comment]
![image](https://user-images.githubusercontent.com/40708551/123367186-273cb500-d597-11eb-8f2a-7a8cb00df5db.png)

**Comment by iamayushdas** [comment]
> > Thirdly, it is not a good idea to put a visible mark on an obvious place. I just spend some time on this issue and get an idea:
> 
> 
> 
> As for this, because I haven't experienced this case, then it's ok for me to do this (is Docusarus using this? @iamayushdas) Waiting for more suggestions :) 
> 
> 
> 
> cc @liuxiran @bzp2010 @lilien1010 @tokers @Yiyiyimu @gxthrj
