### ISSUE TITLE
improve: unform id's for all the sub projects

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#382]
**Actual Behaviour**

1. there is no uniform id's for md pages
2. clicking on java-runner shows the helmchart navigation name

**Expected Behaviour**

id's should be particular and unform for every sub-projects like dashboard, ingress-controller, also this will fix the above [2]

**Steps to reproduce it**

clicking on java-runner shows the helmchart navigation name

**Screenshots of the issue**

![scrnli_24_06_2021_12-04-27](https://user-images.githubusercontent.com/40708551/123214832-5397f900-d4e5-11eb-9181-33c84db1c0da.png)

**Would you like to work on the issue?**
yes, i am working on it

**Comment by juzhiyuan** [comment]
I reproduced this bug, thanks!

**Comment by iamayushdas** [comment]
closing this as the issue is reopened #363
