### ISSUE TITLE
feature request: refine code block copy button behaviour to ignore the leading `$`

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#392]
Currently docusaurus code block copy button would copy all texts including the leading dollar sign, so users could not run commands by simple copy and paste.
![image](https://user-images.githubusercontent.com/34589752/123570658-b106a100-d796-11eb-8d21-66be0faf0105.png)

A easy option is to remove all the dollar sign, but it would lead to messy structure in code blocks, making commands and results the same. So a better method could be refining code block copy button behavior to ignore leading `$`, as [discussed in docusaurus](https://github.com/facebook/docusaurus/issues/1745#issuecomment-546798830)

**Comment by Yiyiyimu** [comment]
Hi @iamayushdas are you interested in working on this problem~

**Comment by iamayushdas** [comment]
I see that people stuck into this has opted to trim the ` $` , I would like to  give a try to fix this.

**Comment by iamayushdas** [comment]
On researching,Many of the websites under facebook like create-react-app , relay, flow , uses the code snippet without `$`

**Comment by Yiyiyimu** [comment]
> On researching,Many of the websites under facebook like create-react-app , relay, flow , uses the code snippet without `$`

Thank you for your time! I think README/getting-started/how-to-build/install-dependencies will not contain a complex code structure so it would be cool to me to remove leading `$` there.

BTW, I just remembered I create a relative PR https://github.com/apache/apisix/issues/4076 🤣

**Comment by iamayushdas** [comment]
Should i work on it?

**Comment by Yiyiyimu** [comment]
> Should i work on it?

Sure thanks for your help!!

**Comment by iamayushdas** [comment]
can we also change the format of our code blocks @Yiyiyimu 

from this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40708551/125547714-c4c9d65c-09fb-4ec6-a4ff-85e45f160b05.png">



to this: 

This adds the `title` to code blocks, we don't have to write the filename or instructions regarding code snippet in (#comment) format

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40708551/125547801-dc235545-2b07-40b4-a95e-939efa3665f2.png">

**Comment by Yiyiyimu** [comment]
Cool @iamayushdas but could we make it work for part of the code blocks, since I think in APISIX most code blocks don't need to clarify its file name

**Comment by iamayushdas** [comment]
> Cool @iamayushdas but could we make it work for part of the code blocks, since I think in APISIX most code blocks don't need to clarify its file name

We could use those comments as a title, how is it?

**Comment by Yiyiyimu** [comment]
> We could use those comments as a title, how is it?

Like I think we don't need to add title for github.com/apache/apisix-docker/pull/194

**Comment by SkyeYoung** [comment]
Any update here? It's been a long time.

**Comment by juzhiyuan** [comment]
> Any update here? It's been a long time.

Would you like to take this one?

**Comment by SkyeYoung** [comment]
@juzhiyuan in fact it's not easy to copy but ignore the `$`. We need parse the code, or use a different structure.

**Comment by SkyeYoung** [comment]
I think we should close this issue, because:

1. If we keep the existing code format, we inevitably need to parse the code. Then we have to change the core code of docusaurus, and this will bring difficulties to subsequent upgrade.
2. If we change the code format, this requires modifying too many documents.

In summary, It is unlikely to solve this problem at present.

@juzhiyuan WDYT?

**Comment by juzhiyuan** [comment]
Hi, there is a lot of documentation containing code blocks with `shell` and `output.`, so I will close this issue and cc @hf400159 @navendu-pottekkat to take a look: this is one point on the documentation style guide. 🙏 😉

**Comment by pottekkat** [comment]
@juzhiyuan Yes. We are including this in the style guide and would be using more of Docusaurus' features.
