### ISSUE TITLE
Feature added: need reviews

### ISSUE THREAD

**Issue by iamayushdas** [apache/apisix-website#394]
Earlier our documentation site was just site, now its a cross-platform app(paw) too, supports 

supports: 

- [x] desktop app (macOS, Windows, Linux)
- [x] native app (iOS, android)

https://apisix-pwa.netlify.app

should I push this to the repo?

@juzhiyuan @Yiyiyimu 

screenshots: 

![IMG_2712](https://user-images.githubusercontent.com/40708551/123808837-ba1a7e00-d90e-11eb-9022-008dfb251d1a.PNG)

![Screenshot from 2021-06-29 19-18-37](https://user-images.githubusercontent.com/40708551/123809425-390fb680-d90f-11eb-962c-bb3a645ea0da.png)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40708551/123810000-b2a7a480-d90f-11eb-9bb4-72c5234d8c69.png">

**Comment by juzhiyuan** [comment]
🤔 if the documentation gets cached and offline?

**Comment by iamayushdas** [comment]
> 🤔 if the documentation gets cached and offline?

Not right now, i just needed a review on this

**Comment by Yiyiyimu** [comment]
I believe the offline support could be pretty useful~
BTW is there any reason we don't discuss or review on the pull request page 🤣

**Comment by 1502shivam-singh** [comment]
> 🤔 if the documentation gets cached and offline?

This would be really cool. We would then have our very own documentation app. You know, like a doc-book.

**Comment by liuxiran** [comment]
sound cool @iamayushdas ~, if you can provide a more detailed plan includes:
* why we need to do this and what benefits will bring to our document site
* what you will do at the code level

that will be better and  more easier for us to judge whether we could receive this feature, thanks~

**Comment by iamayushdas** [comment]
> sound cool @iamayushdas ~, if you can provide a more detailed plan includes:
> 
> * why we need to do this and what benefits will bring to our document site
> * what you will do at the code level
> 
> that will be better and more easier for us to judge whether we could receive this feature, thanks~

for the code plan - https://github.com/apache/apisix-website/pull/395

**Comment by juzhiyuan** [comment]
closed due to https://github.com/apache/apisix-website/pull/395#issuecomment-933405148
