### ISSUE TITLE
feature request: Add Chinese and English version of the website

### ISSUE THREAD

**Issue by Serendipity96** [apache/apisix-website#402]
**Actual Behaviour**

1. When I toggle button to change Chinese and English versions of the website，only the navigation bar has changed，the content of website did not change. 
2. When I choose English website，I hope read English blogs，but now Chinese and English blogs mixed.

**Expected Behaviour**

Switch language to show the website and blogs of the corresponding language version.

**Screenshots of the issue**

 

![image](https://user-images.githubusercontent.com/23514812/124564211-69a5a200-de73-11eb-8a7d-87cc5d16d6d5.png)
![image](https://user-images.githubusercontent.com/23514812/124564264-7924eb00-de73-11eb-991c-f011b676eccd.png)

**Comment by iamayushdas** [comment]
@Serendipity96 would you like to work on this?

**Comment by Serendipity96** [comment]
> @Serendipity96 would you like to work on this?

Sorry, I'm afraid not.

**Comment by SkyeYoung** [comment]
Looks like this can be closed.
