### ISSUE TITLE
feature: update download page to add apisix-java-plugin-runner

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-website#406]
**Actual Behaviour**

 

**Expected Behaviour**

The download page shows the download information of apisix-java-plugin-runner.
 

**Steps to reproduce it**

 

**Screenshots of the issue**

 

**Would you like to work on the issue?**

**Comment by iamayushdas** [comment]
I just checked , no download information of apisix-java-plugin-runner is there

**Comment by tzssangglass** [comment]
There is a delay, now there is

**Comment by juzhiyuan** [comment]
@iamayushdas Please help to check if there have the correct configuration for that repo, if not, please help or tell @tzssangglass what need to do next :)

**Comment by iamayushdas** [comment]
@tzssangglass can you send screenshots of your issue

**Comment by tzssangglass** [comment]
hi @iamayushdas , the archive [archive](https://archive.apache.org/dist/apisix/) page has java-plugin-runner resource, 
![image](https://user-images.githubusercontent.com/30819887/125171184-60a33080-e1e5-11eb-9533-710824037aa8.png)

and I  want to add a download block at https://apisix.apache.org/downloads after APISIX Ingress Controller

**Comment by iamayushdas** [comment]
Oh okay okay, sorry my bad, i was getting you wrong, will add that download block next morning

**Comment by iamayushdas** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/40708551/125184326-519a9d80-e23a-11eb-9677-9658265f8e22.png">

naming has been done wrongly

it should've been started with **apache**-..  @Yiyiyimu @juzhiyuan @membphis

**Comment by juzhiyuan** [comment]
What should we do next? 🤔

**Comment by iamayushdas** [comment]
> What should we do next? 🤔

1. we can rename the file names by just adding apache in front of that
2. also we could change this below piece of code by adding keys in docusaurus.config.js configuration and then importing it to this code

<img width="576" alt="image" src="https://user-images.githubusercontent.com/40708551/125189335-35582a00-e255-11eb-8094-107f501e24f2.png">

@juzhiyuan

**Comment by juzhiyuan** [comment]
ok, continue plz.

**Comment by iamayushdas** [comment]
> ok, continue plz.

Which one, it would be great to change the name, who has the access to change the name may i know?

**Comment by juzhiyuan** [comment]
Hi @tzssangglass, the link under this site https://archive.apache.org/dist/apisix/java-plugin-runner/0.1/ has to be started with `apache-apisix-xx` or it will be rendered as a broken link, because it's missing the `apache-` prefix.

BTW, @iamayushdas I would prefer refactoring this part so we could choose which hyperlink we should use, instead of auto-rederening.

**Comment by juzhiyuan** [comment]
We could maintain a JSON/js file and it contains all download links.

**Comment by tzssangglass** [comment]
> https://archive.apache.org/dist/apisix/java-plugin-runner/0.1/

@spacewander , maybe `apisix-java-plugin-runner` should be renamed to `apache-apisix-java-plugin-runner`. But for files that have been released, I don't know what to do, will changing the name affect md5 and gpg validation?

**Comment by iamayushdas** [comment]
> We could maintain a JSON/js file and it contains all download links.

Yes i agree, we could also do that.

**Comment by spacewander** [comment]
> 
> 
> Hi @tzssangglass, the link under this site [archive.apache.org/dist/apisix/java-plugin-runner/0.1](https://archive.apache.org/dist/apisix/java-plugin-runner/0.1/) has to be started with `apache-apisix-xx` or it will be rendered as a broken link, because it's missing the `apache-` prefix.
> 
> BTW, @iamayushdas I would prefer refactoring this part so we could choose which hyperlink we should use, instead of auto-rederening.

The problem is, we voted for the `apisix-java-plugin-runner-0.1.0-src.tgz`. If what people actually download is `apache-apisix-java-plugin-runner-0.1.0-src.tgz`, I can't ensure it complies with Apache's rules.

> 
> 
> > [archive.apache.org/dist/apisix/java-plugin-runner/0.1](https://archive.apache.org/dist/apisix/java-plugin-runner/0.1/)
> 
> @spacewander , maybe `apisix-java-plugin-runner` should be renamed to `apache-apisix-java-plugin-runner`. But for files that have been released, I don't know what to do, will changing the name affect md5 and gpg validation?

Yes, change the name will affect the sha512 checksum file.

If we need to use a new name, we need to start another vote.

**Comment by juzhiyuan** [comment]
I don't think we need a new VOTE, just updating the Website and maintain a download links file, this is the easiest and clearer way for contributors to maintain the download page.

**Comment by iamayushdas** [comment]
Agree with @juzhiyuan sir

**Comment by juzhiyuan** [comment]
anyone would like to take this issue?

**Comment by iamayushdas** [comment]
> anyone would like to take this issue?

will do this
