### ISSUE TITLE
check out why auto-update docs doesn't work

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#407]
**Actual Behaviour**

We are using `cron` to auto-update docs here: https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml#L14

But it doesn't work now 🤔 according to the `asf-site`'s commit history, no auto-update anymore.

**Expected Behaviour**

It should work as expected.

**Comment by juzhiyuan** [comment]
cc @iamayushdas to have a check

**Comment by juzhiyuan** [comment]
I just checked this page: https://github.com/apache/apisix-website/actions/workflows/deploy.yml

![image](https://user-images.githubusercontent.com/2106987/125059150-9957e280-e0dd-11eb-81d7-fde0d691c706.png)


And the `cron` works, but when you click to see the detail, you will find that the `Deploy` step is skipped, e.g https://github.com/apache/apisix-website/runs/3015733766?check_suite_focus=true

![image](https://user-images.githubusercontent.com/2106987/125059247-aecd0c80-e0dd-11eb-82a4-b5ffd2f5d3eb.png)

**Comment by juzhiyuan** [comment]
Maybe this issue is related to https://github.com/apache/apisix-website/actions/runs/1014046063/workflow#L42 🤔 

We use `github.event_name == 'push'` to check the deploy step is valid (because contributors who have privileges could push codes), what should we change?

**Comment by juzhiyuan** [comment]
How to allow `event_name == 'push'` or `push from Action's cron job`? 🤔

**Comment by juzhiyuan** [comment]
need @Yiyiyimu @liuxiran 's help 🤣

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes

**Comment by Yiyiyimu** [comment]
I think we could change it to
```diff
- if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+ if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'schedule'
```

Ref: https://github.community/t/how-to-set-schedule-event-for-two-branches-and-push-pull-request-events-for-only-one/18267/2
