### ISSUE TITLE
feature: support Plugins Hub

### ISSUE THREAD

**Issue by Serendipity96** [apache/apisix-website#409]
**Actual Behaviour**

APISIX has many plugins, but there is no list of plugins on the website.

**Expected Behaviour**

- Add a tab on the navbar to the home page.
- There is a list of all plugins Under the tab. 
- Click on any plugin, jump to the readme or get started tutorial.

**Screenshots of the issue**

 ![image](https://user-images.githubusercontent.com/23514812/125260282-c4873f80-e332-11eb-91fb-4427e31fae93.png)

**Comment by iamayushdas** [comment]
its there, http://apisix.apache.org/docs/apisix/getting-started , you can close this issue now

**Comment by iamayushdas** [comment]
also @Serendipity96 I got to know you need wall image of all companies, any update

**Comment by KishaniKandasamy** [comment]
@Serendipity96 you meant something similar to https://docs.konghq.com/hub/? **a  list of plugins**.If yes I would like to work on this issue:)

**Comment by Serendipity96** [comment]
> its there, http://apisix.apache.org/docs/apisix/getting-started , you can close this issue now

Now, the list of plugins is hidden too deep and hard to find. We support more than 50 plugins and want more people to know about the plugins.

**Comment by Serendipity96** [comment]
> @Serendipity96 you meant something similar to https://docs.konghq.com/hub/? **a list of plugins**.If yes I would like to work on this issue:)

Yes. Cool!

**Comment by Serendipity96** [comment]
> also @Serendipity96 I got to know you need wall image of all companies, any update

Yes, I am arranging the order of the images.

**Comment by iamayushdas** [comment]
> > its there, http://apisix.apache.org/docs/apisix/getting-started , you can close this issue now
> 
> 
> 
> Now, the list of plugins is hidden too deep and hard to find. We support more than 50 plugins and want more people to know about the plugins.

I understand but I don't like the way of adding it specially, BTW where do you want to put those plugins, in homepage or somewhere else?

**Comment by iamayushdas** [comment]
> > also @Serendipity96 I got to know you need wall image of all companies, any update
> 
> 
> 
> Yes, I am arranging the order of the images.

Okay

**Comment by Serendipity96** [comment]
> > > its there, http://apisix.apache.org/docs/apisix/getting-started , you can close this issue now
> > 
> > 
> > Now, the list of plugins is hidden too deep and hard to find. We support more than 50 plugins and want more people to know about the plugins.
> 
> I understand but I don't like the way of adding it specially, BTW where do you want to put those plugins, in homepage or somewhere else?

**Comment by Serendipity96** [comment]
> > > its there, http://apisix.apache.org/docs/apisix/getting-started , you can close this issue now
> > 
> > 
> > Now, the list of plugins is hidden too deep and hard to find. We support more than 50 plugins and want more people to know about the plugins.
> 
> I understand but I don't like the way of adding it specially, BTW where do you want to put those plugins, in homepage or somewhere else?

I think these plugins are meaningful for developers and the community. We should show them on the homepage navbar.

**Expected Behaviour**

- Add a tab on the navbar to the home page.
- Click the tab to a new page, all plugins are on the page.
- Click on any plugin, jump to the readme or get started tutorial.

**Comment by iamayushdas** [comment]
Navbar is already too much populated, think something else, ik you can

**Comment by iamayushdas** [comment]
Lets know the opinion here-

cc @juzhiyuan @Yiyiyimu

**Comment by KishaniKandasamy** [comment]
> > @Serendipity96 you meant something similar to https://docs.konghq.com/hub/? **a list of plugins**.If yes I would like to work on this issue:)
> 
> Yes. Cool!

Great I will work on this issue

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/125458742-cef19bc9-3194-4102-8751-2679069844f7.png)

Now we have `Docs/Blog/Events/Downloads/Team/Help` on the navbar, how about add a `Resource` or `More` dropdown menu?

Then we could keep: `Blog/Docs/Downloads/Team/Resources`, and put `Plugins Hub/Events/Help` under the `Resources` menu?

**Comment by iamayushdas** [comment]
> ![image](https://user-images.githubusercontent.com/2106987/125458742-cef19bc9-3194-4102-8751-2679069844f7.png)
> 
> Now we have `Docs/Blog/Events/Downloads/Team/Help` on the navbar, how about add a `Resource` or `More` dropdown menu?
> 
> Then we could keep: `Blog/Docs/Downloads/Team/Resources`, and put `Plugins Hub/Events/Help` under the `Resources` menu?

yes that would be far better

**Comment by KishaniKandasamy** [comment]
> ![image](https://user-images.githubusercontent.com/2106987/125458742-cef19bc9-3194-4102-8751-2679069844f7.png)
> 
> Now we have `Docs/Blog/Events/Downloads/Team/Help` on the navbar, how about add a `Resource` or `More` dropdown menu?
> 
> Then we could keep: `Blog/Docs/Downloads/Team/Resources`, and put `Plugins Hub/Events/Help` under the `Resources` menu?

nice

**Comment by 1502shivam-singh** [comment]
> I think these plugins are meaningful for developers and the community. We should show them on the homepage navbar.
> 
> **Expected Behaviour**
> 
> * Add a tab on the navbar to the home page.
> * Click the tab to a new page, all plugins are on the page.
> * Click on any plugin, jump to the readme or get started tutorial.

I think this stuff belongs to the docs, as in a special section to this, which already is present as a matter of fact.
What we can actually do is focus on making this section more apparent given that APISIX boasts of a pluginised workflow.

I think a better aproach would be to do this stuff where it is, like we have a plugin library on the dashboard right, so we lead the user to the plugin doc straight from the dashboard rather than making them search it on the site. This works for the dashboard users. For the rest, docs are pretty clear I guess.

**Comment by juzhiyuan** [comment]
@1502shivam-singh Yes, you are right, but another point to add Plugins Hub is because, we could let more people who haven't been using the Dashboard know, what plugins it contains, it's attractive for visitors :) I would agree to support Plugins Hub on the Apache APISIX Webiste.

**Comment by iamayushdas** [comment]
> @1502shivam-singh Yes, you are right, but another point to add Plugins Hub is because, we could let more people who haven't been using the Dashboard know, what plugins it contains, it's attractive for visitors :) I would agree to support Plugins Hub on the Apache APISIX Webiste.

Agree +1

**Comment by 1502shivam-singh** [comment]
> @1502shivam-singh Yes, you are right, but another point to add Plugins Hub is because, we could let more people who haven't been using the Dashboard know, what plugins it contains, it's attractive for visitors :) I would agree to support Plugins Hub on the Apache APISIX Webiste.

I am with this, it is just that I want this to stick more in the docs side of things. My main point is on making it more apparent yet keeping the navs clean. 

If it's about attracting more visitors and making plugins more accessible then I feel the suggestion you provided above about including it in the navbar under resources sounds more cleaner rather than making a whole separate tab for plugins.

**Comment by juzhiyuan** [comment]
fine, @1502shivam-singh then do you have time to lead this? I see you have lots of design experience, we may need a prototype first 😊

**Comment by 1502shivam-singh** [comment]
Sure, happy to help. So we will need a high level wireframe of how this library kind of page will look like. Will share here soon

**Comment by 1502shivam-singh** [comment]
A quick wireframe can base development on this.

![Plugin-lib](https://user-images.githubusercontent.com/57267960/125851491-da8b970b-c845-42a2-a0dd-c3ddf93dd4dd.png)

Some background, in the plugin cards those crossed boxes are where the plugin icon will go. The structure of cards is like this -> 
>> Plugin icon
>> Plugin name
>> Small concise description of plugin (taken from docs)
>> Read more, a link to the related plugin in docs like - https://apisix.apache.org/docs/apisix/plugins/#pluginName

I was thinking of adding a "search plugin by name" option but have dropped it for now in this one given that the plugin lists are not so long really. If we do need one we can add a global search option on plugins regardless of type.

If you want to see the figma board - https://www.figma.com/file/Z46kvRBwmA4PS5FnCCfTrU/Plugin-library?node-id=3%3A2

**Comment by juzhiyuan** [comment]
That's cool, and will it connect to the plugin docs?

**Comment by 1502shivam-singh** [comment]
Yes, as I said in the card structure. Read more leads to related plugin in docs  (https://apisix.apache.org/docs/apisix/plugins/#pluginName)

**Comment by 1502shivam-singh** [comment]
I made some very tiny subtle edits (image above also updated) like spacings and removed APISIX from title as it's just repititive information. If any one wants to submit some comments or suggest edits feel free to click the figma board link above (pasting here too - https://www.figma.com/file/Z46kvRBwmA4PS5FnCCfTrU/Plugin-library?node-id=3%3A2). This maybe seems pretty good to start with, anyone who wants to work on this issue can maybe base coding on this after little more discussion I guess.

**Comment by juzhiyuan** [comment]
looks good to me!

**Comment by 1502shivam-singh** [comment]
I guess we are good to go then 🚀

**Comment by juzhiyuan** [comment]
ya

**Comment by KishaniKandasamy** [comment]
> > > @Serendipity96 you meant something similar to https://docs.konghq.com/hub/? **a list of plugins**.If yes I would like to work on this issue:)
> > 
> > 
> > Yes. Cool!
> 
> Great I will work on this issue

@juzhiyuan Shall I work on this issue?

**Comment by juzhiyuan** [comment]
Sure, and using this ptototype?

https://github.com/apache/apisix-website/issues/409#issuecomment-880620378

**Comment by KishaniKandasamy** [comment]
> Sure, and using this ptototype?
> 
> [#409 (comment)](https://github.com/apache/apisix-website/issues/409#issuecomment-880620378)

Yes
