### ISSUE TITLE
The release date of plugin runners are incorrect

### ISSUE THREAD

**Issue by spacewander** [apache/apisix-website#419]
**Actual Behaviour**

 See below

**Expected Behaviour**

apisix-go-plugin-runner-0.1.0 was released on 2021-07-15.
apisix-java-plugin-runner-0.1 was released on 2021-07-09

**Steps to reproduce it**

 

**Screenshots of the issue**

 
<img width="859" alt="微信截图_20210722120615" src="https://user-images.githubusercontent.com/4161644/126588700-ef74887d-345b-4423-9101-7819b4009494.png">

**Would you like to work on the issue?**

**Comment by iamayushdas** [comment]
okay it will be fixed, thanks for suggesting changes @spacewander
