### ISSUE TITLE
Put FAQ entries on the navbar

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#422]
Hi, in order to make the FAQ entry more clearly, we are going to put the FAQ menu here

![image](https://user-images.githubusercontent.com/2106987/126744801-937f9e8a-3ab7-4b81-a9b8-b55300541f34.png)

**Steps**
1. Find out which project has the FAQ document? All repos here: https://github.com/apache/?q=apisix&type=&language=&sort=
2. Add the `FAQ` dropdown menu between `Docs` and `Blog` for now, when hovering the menu, it will show all projects which have the FAQ file. Like this:
![image](https://user-images.githubusercontent.com/2106987/126745163-93280281-0363-4c07-96be-2d9fb6c71d43.png)
3. When clicking one of the FAQ's submenus, it will lead to the Docs site, like https://apisix.apache.org/docs/apisix/FAQ

**Comment by iamayushdas** [comment]
Nice thought 👍🏻

**Comment by Baoyuantop** [comment]
I am trying to solve ～
