### ISSUE TITLE
Support showing Project's name on the navbar

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#424]
When we visit FAQ from the `FAQ` dropdown:

![image](https://user-images.githubusercontent.com/2106987/126761231-f6d6a5d5-6a2f-4c8f-abfc-cff1a5c27dff.png)

It will show `Docs`:

![image](https://user-images.githubusercontent.com/2106987/126761430-72415e68-238c-4cc9-9039-f46e9eefae91.png)

**Expected behavior**

It will show the target repo's name:

![image](https://user-images.githubusercontent.com/2106987/126761473-ad74d5bb-96df-4642-b42b-4129dc0eb4d6.png)

Maybe related to https://github.com/apache/apisix-website/blob/master/website/src/theme/DocPage/index.js#L41 ?

**Comment by juzhiyuan** [comment]
@Baoyuantop Do you have time to take a look?

**Comment by Baoyuantop** [comment]
> @Baoyuantop Do you have time to take a look?

Ok, let me take a look

**Comment by Baoyuantop** [comment]
Waiting for https://github.com/apache/apisix-ingress-controller/pull/605
