### ISSUE TITLE
bug: Refreshing the page after closing the 200 contributor guide causes flickering

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-website#428]
**Actual Behaviour**

The pop-up window at the bottom right corner of the current home page of the official website will flash when the page is refreshed after being closed manually.

**Expected Behaviour**

There should be no flashing of the refresh page guide window after clicking on the close guide window

**Steps to reproduce it**

1. Click to close 200 contributors Lead
![Snip20210727_25](https://user-images.githubusercontent.com/72343596/127097102-abe95780-4d31-4029-b4d5-d907fcf9bc62.png)

2. Refresh the page
3. 200 Contributor guide component flashes

**Screenshots of the issue**

 

**Would you like to work on the issue?**

**Comment by Baoyuantop** [comment]
This issue is relatively easy to solve, I will send a PR
