### ISSUE TITLE
style: Home page pop-ups removed

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-website#443]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/72343596/128970970-e343628a-8ba3-4c5e-ae39-f00854af4297.png)

**Expected Behaviour**

1. easy to reuse in the future, pull out as a component stand alone
2. Remove the style from the current home page

**Steps to reproduce it**

 

**Screenshots of the issue**

 

**Would you like to work on the issue?**

**Comment by guoqqqi** [comment]
Hi, @Baoyuantop Do you have time to solve the problem?

**Comment by Baoyuantop** [comment]
> Hi, @Baoyuantop Do you have time to solve the problem?

sure ～
