### ISSUE TITLE
discuss: community review of improved apisix-website on copywriting

### ISSUE THREAD

**Issue by 1502shivam-singh** [apache/apisix-website#450]
Hi all, just finished up with my GSoC project of improving the apisix-website (Redesign and code), would be happy to receive reviews from you all, specifically on copywriting and minor issues like broken links (if any) etc. 

Here is the website - https://apisix-re.netlify.app/
Just to mention, all the interactions and animations (WebGL, CSS) you see on this website are my own, implemented from scratch in code. Clarifying for the sake of copyright issues, if any.

I am open to suggestions/changes in copywriting based on reviews by the community.
Hope you like this new perspective of Apache APISIX :)

cc @juzhiyuan , @Yiyiyimu 
(If you are aware of community members that might be free/willing to review please mention them, posting here as last time I posted on mailing-list it good mixed and lost with the other mails)

EDIT : For easier review of copywriting check out this PR - #477

**Comment by liuxiran** [comment]
@1502shivam-singh your redesign of our website is really cool~what particularly attracted me was the middle section of the product description and Learn from developers parts.
![image](https://user-images.githubusercontent.com/2561857/129600291-fcee710b-f2d4-4a90-b6f1-17d920730400.png)


and it would be better to adjust the layout of the first screen  or enrich the content 
![image](https://user-images.githubusercontent.com/2561857/129601044-c7f6cb96-79de-4fcd-b2cf-8225963cc449.png)

together with the last part of the page: Be a part of building APISIX
![image](https://user-images.githubusercontent.com/2561857/129601640-63755eaa-2f94-417e-9936-1ca6f563ee00.png)

**Comment by 1502shivam-singh** [comment]
Thanks @liuxiran for the review. 
Though I see some irregularities between the actual site and the shots you have provided. For instance - 
A shot of the top section - 

![Hero](https://user-images.githubusercontent.com/57267960/129613910-d51684e5-ce07-43f2-9c04-9cf2fd802a6c.png)

Here that flow infographic on the right animates going down, with an interaction that a little bump follows the movement of the 
mouse when hovered over that canvas. 
The flow infographic in your shot appears almost non existent or blurred out 😕

GitHub invite section - 

![github](https://user-images.githubusercontent.com/57267960/129614403-068f24db-e395-4fad-9346-b3f22b785ecc.png)

The sphere rotates and is actually interactable by mouse, you can rotate it with mouse drags. I see some misalignments in your shot in this one.

Also something I noticed - 
The curved line svg appears behind APISIX's design and animates with color changes, but in your shot it appears down behind "Why APISIX".
![arch](https://user-images.githubusercontent.com/57267960/129614656-13b8b905-3952-41b5-a168-dd893de42d70.png)

Now for providing some perspective here, I have tried keeping a minimalistic and clean design here, given the seriousness of the product APISIX. 
The flow in top section is more of a metphor to the smooth, frictionless and synchronised performance of APISIX. It's a subtle element that I came up with after alot of brainstorming on what to put there, and this made most sense to me.

Please match-up if same layout is visible to you too and whether animations and interactions are functioning or not. 
Also, if you have time, could you review the text-content of the website. so as to not supply any wrong information to the viewer (I have checked myself, but more eyes are always better 😊)

**Comment by 1502shivam-singh** [comment]
Uploading recorded-site.mp4…

**Comment by 1502shivam-singh** [comment]
Might be an overkill 😅, but please bear with me on this, could you check out this recorded video of the site for matching up layout and interactions

https://user-images.githubusercontent.com/57267960/129620073-3f0f181a-77e2-4983-9cb5-8b3d4880b7bc.mp4

**Comment by Yiyiyimu** [comment]
Nice design @1502shivam-singh! Do you mind creating a markdown version of all the text in the new design and create a not-merge PR for it. I think the text part review could be easier with that.

Some suggestions from my preference 🤣 
1. the right part of the architecture graph seems a little unbalanced, since the all contents are in the upper part. Also we might could change `APISIX has dynamic routing and plug-in hot loading` to `APISIX has dynamic routing and hot-loading plugins` to keep the "adj.-n." format
![image](https://user-images.githubusercontent.com/34589752/129620048-132eabb8-6852-42d7-8b63-b0380a469779.png)
2. Seem missing a period here: "It’s opensource and ever evolving(.) feel free to contribute". And also we need a screenshot of dashboard in higher resolution
![image](https://user-images.githubusercontent.com/34589752/129620897-c1d71f82-6506-4247-86c2-8a9a8229b9ff.png)
3. The graph of `User Flexible` seems not correct. The description of it seems related to low code (the graph used in "Pluginised workflow").
4. the description here is not so correct. The high performance should come from radixtree-route-matching and also etcd, not from plugins. Also, built-in plugins and json schema is more related to convenience so apisix could be used out-of-box.
![image](https://user-images.githubusercontent.com/34589752/129621580-f981928c-7647-4e34-8b0f-9ce682dbf06d.png)
5. maybe we could have a button for the `check us out` or people might not regard it as clickable
![image](https://user-images.githubusercontent.com/34589752/129622209-fd352b8d-98b6-4029-b09d-5aab85215e6a.png)

**Comment by 1502shivam-singh** [comment]
> Nice design @1502shivam-singh! Do you mind creating a markdown version of all the text in the new design and create a not-merge PR for it. I think the text part review could be easier with that.

Woh, really nice suggestion, you would then be able to provide changes in a better way using github UI. Excellent idea, on it. Also to avoid fiasco with the actual apisix-website repo, I would make a PR on my own repo, and will share link here.

> 1. the right part of the architecture graph seems a little unbalanced, since the all contents are in the upper part. Also we might could change `APISIX has dynamic routing and plug-in hot loading` to `APISIX has dynamic routing and hot-loading plugins` to keep the "adj.-n." format

Okay, i guess pulling the etcd cluster little bit down to align with bottom edge APISIX block should do. Agreed with the latter.

> 2. Seem missing a period here: "It’s opensource and ever evolving(.) feel free to contribute". And also we need a screenshot of dashboard in higher resolution

Noted. I would say a comma maybe, but yeah i got you. On the screenshot, yeah on it, I guess compression did hurt it too much.

> 3. The graph of `User Flexible` seems not correct. The description of it seems related to low code (the graph used in "Pluginised workflow").

Hmm, i was actually referencing the dual ability of code and drag and drop of APISIX. You are right, this one actually needs copywriting changes, like to -  `The APISIX dashboard is flexible to the user demand, providing option to write code to create custom modules as per your needs, alongside the existing no-code toolchain`

> 4. the description here is not so correct. The high performance should come from radixtree-route-matching and also etcd, not from plugins. Also, built-in plugins and json schema is more related to convenience so apisix could be used out-of-box.

The perspective I needed, thanks. Okay, need to modify this one. How about - `Apache APISIX uses radixtree-route-matching and etcd under the hood to provide you the ability to create high speed synchronized systems. From routing to built-in plugins, all these are designed and implemented to be uber performant with the minimum latency possible.`

> 5. maybe we could have a button for the `check us out` or people might not regard it as clickable

Oops missed this. Earlier I thought of a red link as usually seen elsewhere, but yeah a button seems more viable

Thanks for the detailed review, will share PR link here.

**Comment by 1502shivam-singh** [comment]
Check out this PR if you want to review the copywriting - https://github.com/1502shivam-singh/apisix-website-redesign/pull/11

**Comment by Yiyiyimu** [comment]
I believe the copywriting changing all looks good to me! 

Besides, maybe you could move the PR here in this repo so more people could notice that

**Comment by 1502shivam-singh** [comment]
> Besides, maybe you could move the PR here in this repo so more people could notice that

Done, checkout #477
