### ISSUE TITLE
support 404 page for website

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#460]

**Comment by Amishakumari544** [comment]
could you please provide any 404 UI @liuxiran or should I design by myself to add this page??

**Comment by iamayushdas** [comment]
Hi @Amishakumari544, you could explore the apisix website and get some idea about it by yourself. 
Also you could comment your designs here for our reviews.
Thanks a lot

**Comment by Amishakumari544** [comment]
Hi @iamayushdas I have designed one UI for 404 could please review once if it is ok to code or not???
Link is here:
https://www.figma.com/file/l6aK7cLCDpJWiuzYnu43ZN/Untitled?node-id=101%3A2

**Comment by iamayushdas** [comment]
Its good, but could you play around with apisix icon in 404 page?

**Comment by Amishakumari544** [comment]
like can you give some example I am not getting you what should I change in this?

**Comment by iamayushdas** [comment]
Lemme cc @liuxiran @juzhiyuan @guoqqqi for review on it

**Comment by 1502shivam-singh** [comment]
> https://www.figma.com/file/l6aK7cLCDpJWiuzYnu43ZN/Untitled?node-id=101%3A2

This looks too generic for reasons -

- Uses generic stock infographics from free-to-use websites (nothing bad with this), that don't have much correlation with APISIX in general. If you don't want to do something custom or are out of ideas try adding images that have some connection with APISIX's background (you might want to do a bit of research to get a better background)

- This doesn't really give me the right vibes for a product of the seriousness of APISIX. Ofcourse you can get a bit loose and creative but that would need something different than the provided.

My remark would be, try to play around with the original `Page Not Found` template used in docusaurus configured websites and make additions to it. Minimalistic and clean design, with subtle interactions would be appreciated given we don't want people to spend hours on our 404-page :P, but still, appreaciate it and move on.

**Comment by Amishakumari544** [comment]
ok @1502shivam-singh  then can you suggest any website that how should 404 look like this ?
I used this by a free website and redesign it its not the same as looked in the website but please suggest which type of 404 page you want?

**Comment by 1502shivam-singh** [comment]
> I used this by a free website and redesign it its not the same as looked in the website but please suggest which type of 404 page you want?

As I mentioned above, try to play around with the original Page Not Found template used in docusaurus configured websites and make additions to it (To see this page checkout - https://deploy-preview-395--apisix.netlify.app/docs/dashboard/USER_GUIDE, trying making additions to this page).
Minimalistic and clean design, with subtle interactions would be appreciated. For instance, as mentioned above by Ayush, you can do something with APISIX's logo or something of your own is also welcome).

**Comment by liuxiran** [comment]
Agree with @1502shivam-singh, we can first make all the 404 page redirect to the original Page Not Found template, in fact we will see 
![image](https://user-images.githubusercontent.com/2561857/130313975-71eeb18c-a390-45f9-bc55-f156e333d2be.png)
instead of the default 404 page currently


and then welcome to make our 404 page better, thanks

**Comment by juzhiyuan** [comment]
Resolved by https://github.com/apache/apisix-website/issues/1066
