### ISSUE TITLE
Bug: Page Not Found

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#461]
- [ ] https://apisix.apache.org/docs/helm-chart/FAQ/
steps:
1. ![image](https://user-images.githubusercontent.com/2561857/129574211-7e51972c-3f39-44ac-8931-b08b24e9ada5.png)
2. ![image](https://user-images.githubusercontent.com/2561857/129574331-401cda0f-77f4-4f71-a98f-c119b8cda59b.png)

- [ ] https://apisix.apache.org/zh/docs/helm-chart/FAQ/
steps:
1. ![image](https://user-images.githubusercontent.com/2561857/129574518-701f8446-3cff-4561-9937-c39cced65373.png)
2. ![image](https://user-images.githubusercontent.com/2561857/129574616-7dbfb603-9b64-46d5-a5db-2049df74cbaf.png)

**Comment by KishaniKandasamy** [comment]
Hi @liuxiran  ,
It happened due to an unmerged commit https://github.com/apache/apisix-helm-chart/pull/118

**Comment by liuxiran** [comment]
> apache/apisix-helm-chart#118

thanks a lot @KishaniKandasamy  , and the related pr got merged just now, after it deployed, and works ,this issue will be closed

**Comment by liuxiran** [comment]
hi @KishaniKandasamy , website has updated, and the `page not found` has been fixed , thanks a lot

![image](https://user-images.githubusercontent.com/2561857/129672081-c7b4a834-7124-421c-910c-41b20122ed88.png)

while checking the page, I found that there are some typo errors in the `FAQ`, I 'll open other issue to trace it, and welcome to send pr to improve our doc.

**Comment by KishaniKandasamy** [comment]
Sure @liuxiran

**Comment by liuxiran** [comment]
> Sure @liuxiran

tracing issue：https://github.com/apache/apisix-website/issues/471

**Comment by liuxiran** [comment]
close this issue now
fixed by https://github.com/apache/apisix-helm-chart/pull/118
