### ISSUE TITLE
page: failed to load the ico of plugin

### ISSUE THREAD

**Issue by membphis** [apache/apisix-website#462]
uri: https://apisix.apache.org/pluginhub/

![image](https://user-images.githubusercontent.com/6814606/129646740-d4363bbe-0bc5-40c2-abb9-c08038fa3719.png)

**Comment by liuxiran** [comment]
Hi @KishaniKandasamy , since this great feat got merged, there are something wrong with the pics links, would you like to fix them when you have time?

**Comment by liuxiran** [comment]
![image](https://user-images.githubusercontent.com/2561857/129665459-18721eb2-2621-42e3-8adb-c57ef71f1b2f.png)

website updated, it worked now, thanks @Baoyuantop

**Comment by KishaniKandasamy** [comment]
> ![image](https://user-images.githubusercontent.com/2561857/129665459-18721eb2-2621-42e3-8adb-c57ef71f1b2f.png)
> 
> website updated, it worked now, thanks @Baoyuantop

yes Thanks @Baoyuantop
