### ISSUE TITLE
Bug: update home page events list

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#464]
**Actual Behaviour**

Current events did not include the `8.21 shanghai meetup`
 
![image](https://user-images.githubusercontent.com/2561857/129671382-6b8ccb77-6aad-494f-9c10-bafac32a9762.png)

**Expected Behaviour**

- [x] should update it manually
- [ ] should update it automaticly

**Comment by liuxiran** [comment]
please help to update the task 1 first @bzp2010 , thanks a lot~

**Comment by liuxiran** [comment]
reopen this issue for task two, not emergent

before task two ready, need to check wether update configure file together with event

**Comment by juzhiyuan** [comment]
consider resolved
