### ISSUE TITLE
support tag and count for our blog

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#470]
## Actual Behavior

At the moment, our blog only shows the title, author and other information in the summary page, 

for example:

![image](https://user-images.githubusercontent.com/2561857/129780307-2629af94-3063-4839-8512-4ff5b550ac39.png)

## Expected Behavior

We need to add some tags for each blog, and at the same time, viewers can search blogs via tags, so that it will be easier for viewer to get what they want

for example:

https://quickwit.io/blog

![image](https://user-images.githubusercontent.com/2561857/129780490-40d34973-bb40-48bf-a9cb-ac1f5cad9bb9.png)

https://developer.axioms.io/blog

![image](https://user-images.githubusercontent.com/2561857/129781159-19ef2494-908e-4a03-8f0c-a2bddc329461.png)

**Comment by Baoyuantop** [comment]
I found that in the blog type file of Docusaurus, the header of the file allows us to set the [tags field](https://docusaurus.io/docs/blog#adding-posts).

It looks like this when I try to set it up：

![image](https://user-images.githubusercontent.com/30611190/129848579-f52ca425-a1fe-46eb-9838-3775d8ba3f51.png)

And when I select a tag, it will list all the blogs under that tag:

![image](https://user-images.githubusercontent.com/30611190/129848780-0c6b30ab-f106-4937-b3c4-7a5a360ba37d.png)

I think it can solve this demand, all we need to do is to add tags to each blog.

**Comment by juzhiyuan** [comment]
Good!

**Comment by liuxiran** [comment]
cool ~, we can use it as our first edition

**Comment by liuxiran** [comment]
I noticed there are about 4 types blogs in our site, they are:

* release notes and news
e.g. 
https://apisix.apache.org/blog/2021/07/28/release-apache-apisix-2.8-en/
and for this part, I  recommend to move them to `events`, 

* technology
e.g.
https://apisix.apache.org/blog/2021/08/12/Chaos-Mesh-Helps-Apache-APISIX-Improve-System-Stability

* security
e.g.
https://apisix.apache.org/blog/2021/06/17/Apache-APISIX-Dashboard-Access-Control-Bypass-Vulnerability-Announcement

* practical case
e.g.
https://apisix.apache.org/blog/2021/08/09/Apache-APISIX-in-China-Mobile-Cloud
https://apisix.apache.org/blog/2021/07/14/the-road-to-customization-of-Sina-Weibo-API-gateway-based-on-Apache-APISIX

what's your opinion about classification of articles? @Baoyuantop @yzeng25 @Serendipity96 @bzp2010 @KishaniKandasamy @1502shivam-singh  @juzhiyuan @moonming 

Once the categories have been defined we can get to work on this function

**Comment by Serendipity96** [comment]
Awesome!
1. Will the events page also be modified at the same time as the blog page? Do the contents also can be searched, added tags, and see a list of all articles on the events page? 
2. What about change "technology" to 3 tags, "API GateWay" "Ingress Controller" "Service Mesh"?
3. What about change "practical case" to "user case"?

**Comment by yzeng25** [comment]
I agree with the '4 types blogs' as  @liuxiran listed above. In addition, I think we can derive more types out of these 4 when necessary.

**Comment by liuxiran** [comment]
> 1. Will the events page also be modified at the same time as the blog page? Do the contents also can be searched, added tags, and see a list of all articles on the events page?

good catch, actually all posts need tags in our site, and we can first do it in blog page, and Iterate through the detailed classification of articles for each module step by step.

> 2. What about change "technology" to 3 tags, "API GateWay" "Ingress Controller" "Service Mesh"?

This is more focused~! Based on this idea, maybe we also need a tag something called `Peripheral technology`
e.g.
https://apisix.apache.org/blog/2021/06/16/Chaos-Mesh-helps-Apache-APISIX-improve-stability/
https://apisix.apache.org/blog/2021/03/02/get-front-end-test-coverage-with-cypress/

> 3. What about change "practical case" to "user case"?

Agree with it ~!

**Comment by KishaniKandasamy** [comment]
Yes, absolutely! Well  
4 types of blog  looks good to me

**Comment by KishaniKandasamy** [comment]
What about  first separating them into en and zh blogs then we could apply these 4 types blogs in our site  ?

**Comment by liuxiran** [comment]
> What about first separating them into en and zh blogs then we could apply these 4 types blogs in our site ?

yes, separating them into en and zh blogs is necessary, we can start it from this point, and would like to have a try @KishaniKandasamy

**Comment by KishaniKandasamy** [comment]
Sure, I will give a try

**Comment by liuxiran** [comment]
> Sure, I will give a try

ok, assign to you, thanks very much, any questions can be commented here

**Comment by liuxiran** [comment]
hi @KishaniKandasamy, you are currently focused on separating blogs into en and zh right, do you have any problems we can do for you?

**Comment by KishaniKandasamy** [comment]
Yes.Separating blogs into en and zh is okay .but I'm a bit unclear in some places  dividing the **zh blogs into those 4types** due to the language issue :( .Can anyone help me to do this?

**Comment by liuxiran** [comment]
> Yes.Separating blogs into en and zh is okay .but I'm a bit unclear in some places dividing the **zh blogs into those 4types** due to the language issue :( .Can anyone help me to do this?

got you, thanks @KishaniKandasamy , then you can just complete the separating part, and for the tag part , just leave it to @bzp2010 , let's work together to finish it , is that ok for you?

**Comment by KishaniKandasamy** [comment]
yeah that's fine

**Comment by liuxiran** [comment]
> yeah that's fine

glad to hear that, looking forward to your pr @KishaniKandasamy

**Comment by KishaniKandasamy** [comment]
Sure!

**Comment by bzp2010** [comment]
> Yes.Separating blogs into en and zh is okay .but I'm a bit unclear in some places dividing the **zh blogs into those 4types** due to the language issue :( .Can anyone help me to do this?

Hi @KishaniKandasamy. By the way, You can refer to this document for this work. [link here](https://docusaurus.io/docs/i18n/introduction#translation-files-location)

**Comment by KishaniKandasamy** [comment]
> > Yes.Separating blogs into en and zh is okay .but I'm a bit unclear in some places dividing the **zh blogs into those 4types** due to the language issue :( .Can anyone help me to do this?
> 
> Hi @KishaniKandasamy. By the way, You can refer to this document for this work. [link here](https://docusaurus.io/docs/i18n/introduction#translation-files-location)

Thanks . [PR](https://github.com/apache/apisix-website/pull/550) submitted for this task.
