### ISSUE TITLE
Bug: typo errors in helm-chart FAQ page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#471]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/2561857/129673550-5495a89a-7318-4d6a-b98c-d4062d660be3.png)

**Expected Behaviour**

There are two FAQ in the current page, we  expected to use 
`<H3>` , `###` the second level in markdown, to wrap them, and omit their number

![image](https://user-images.githubusercontent.com/2561857/129674753-4b615dc3-687a-4347-aff1-49dafa3226e3.png)

**Comment by KishaniKandasamy** [comment]
I will fix it

**Comment by liuxiran** [comment]
> I will fix it

ok, thanks a lot~
