### ISSUE TITLE
discuss: add apachecon asia 2021 toc and articles

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix-website#472]
**Discuss description**

- Now
First, add an page in the events as the table of contents shared by ApacheCon activities.
Then, add a title, description, sharer, etc. about the shared content, and add a link to an article page with no other link entry.
The article page will be similar to the current existing blog page and contain both articles and videos.
This can be quickly implemented and available on the official website.

- Future
In the future, the active directory page will consider using custom pages to achieve a more flexible and friendly layout.

**Screenshots of the issue**

#### TOC
![image](https://user-images.githubusercontent.com/8078418/129832352-e55f52ce-c6cd-4d47-878d-da07ffff4002.png)

#### Articles (Just like blog)
![image](https://user-images.githubusercontent.com/8078418/129833038-be6eb66a-7586-4f06-9558-e7f8afa4d97c.png)

**Comment by liuxiran** [comment]
* The introduction of tag is a great point, we can add tags to each topic
* It is hard to make decision whether to  put `ApacheCon 2021` to `Blog` or to `Events`, wait for everyone's opinion @juzhiyuan @Serendipity96 @moonming 

Others look good to me~!

**Comment by Serendipity96** [comment]
I think ApacheCon Asia 2021 video would be more appropriate in Events or use a separate tab on nav. What do you think?

**Comment by juzhiyuan** [comment]
How about designing a Resource template?

**Comment by liuxiran** [comment]
> How about designing a Resource template?

good idea~! In fact we have several types of articles now, blogs, events, releases and so on, a distinction should indeed be made for them.

how about improve them in new prs, and we can first post the Apache con online?

@Serendipity96 @juzhiyuan

**Comment by juzhiyuan** [comment]
LGTM, need @Serendipity96's confirmation
