### ISSUE TITLE
Feature required: place the plugin icon image horizontal center in plugins page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#484]
> In addition, maybe it would look better by placing the plugin icon image horizontal center

Agreed, they are not centered completely, feel free to solve this issue. Also one more thing if you could help out with would be really nice , can you reduce the sizes of the plugin thumbnails so that all of them look of the same sizes and bit smaller (currently the icons seem too packed inside the card with less white space all around)

_Originally posted by @1502shivam-singh in https://github.com/apache/apisix-website/issues/478#issuecomment-901317804_

**Comment by foolwc** [comment]
I'm glad to do it.   
- [ ] place the plugin thumbnails in horizontal center;
- [x] reduce the sizes of the plugin thumbnails;

**Comment by juzhiyuan** [comment]
would better provide a design only :)
