### ISSUE TITLE
Request help: I want to view all the blogs index in one page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#490]
**Actual Behaviour**

Rensently, when I visit our [blog page](https://apisix.apache.org/blog), I found that it is hard for me to know what blogs we have, for there are only five blogs in menu list. I have to click `next` button to go to next page 

![image](https://user-images.githubusercontent.com/2561857/130215447-7f7a2f57-7418-4ec4-9317-5548e2077669.png)

I wonder if we can change our blog index page to a guided page, we can found all the blogs, no matter by name list, keyword list, and so on.

**Expected Behaviour**
Help me to found a better organized way easily view all blogs, thanks a lot

**Comment by bzp2010** [comment]
In fact, more items can be displayed here. We only need to adjust them in the configuration file, but the effect is not nice.

We may need to customize the page to solve this problem.

**Comment by 1502shivam-singh** [comment]
> Recently, when I visit our [blog page](https://apisix.apache.org/blog), I found that it is hard for me to know what blogs we have, for there are only five blogs in menu list. I have to click `next` button to go to next page
>
> I wonder if we can change our blog index page to a guided page, we can found all the blogs, no matter by name list, keyword list, and so on.
>
> Help me to found a better organized way easily view all blogs, thanks a lot

So I did some look out and found that the most commonly used strategies are -

- Blogs thumbs come in a list from most recent to past ones, and are paginated to display certain amount on one page. Also, they provide feature to look up blogs under different sub categories
- On demand load of blogs thumbs, like the read more stories thing on google blog (check in link below)

Check out these examples for some ideas and we can discuss on the ones we like.

- https://blog.google/
- https://stripe.com/blog
- https://github.blog/
- https://www.netlify.com/blog/
- https://ionicframework.com/blog/

If we want to go complete vanilla then [React blog website](https://reactjs.org/blog/) is best bet, given that I believe React website is also based on docusaurus (but personally I think their site is really confusing to traverse among blogs, when you have tried blog sections like on our website).
EDIT: React blog is actually based on Gatsby not docusaurus.

**Comment by liuxiran** [comment]
Great @1502shivam-singh , thanks for such careful research~

Among those sites listed above, I prefer https://github.blog/ 

* Categorise blog posts to make it easier for users to focus on target areas faster
* Articles are in chronological order from new to old, so that users can easily see the latest blog posts
* Topping the most popular posts in the current category is also convenient for users to access
* Turn the page to view, in line with user browsing habits
* Global search, pinpointing

actually, we already have global search, list order from new to old and  paging. We need Categorise, it will be the be the cornerstone of our optimisation.

what do you think? 

cc @bzp2010 @KishaniKandasamy @foolwc @yzeng25 @juzhiyuan @moonming @Baoyuantop @guoqqqi @LiteSun @iamayushdas

**Comment by Baoyuantop** [comment]
I prefer https://github.blog/ too. Categorize is a good idea, similar to #470 , we can quickly view the corresponding content by category, so do we still need tags? Or use tags as the first step?

**Comment by yzeng25** [comment]
https://github.blog/ +1

**Comment by juzhiyuan** [comment]
github.blog or blog.google LGTM

**Comment by 1502shivam-singh** [comment]
> Among those sites listed above, I prefer https://github.blog/
> 
> * Categorise blog posts to make it easier for users to focus on target areas faster
> * Articles are in chronological order from new to old, so that users can easily see the latest blog posts
> * Topping the most popular posts in the current category is also convenient for users to access
> * Turn the page to view, in line with user browsing habits
> * Global search, pinpointing
> 
> actually, we already have global search, list order from new to old and paging. We need Categorise, it will be the be the cornerstone of our optimisation.
> 
> what do you think?

Seems like a nice way to move forward. Also the layout of github's blog is very clean, so a similar adaptation with some changes will be highly usable and look nice visually too. +1

Something to add, we can also adapt the strategy used by Google to `load more stories` on the same page. Pagination is good, but it has that context switch, staying on same page while browsing is always better. 

So more like a hybrid of both strategies I mean.

**Comment by 1502shivam-singh** [comment]
> I prefer https://github.blog/ too. Categorize is a good idea, similar to #470 , we can quickly view the corresponding content by category, so do we still need tags? Or use tags as the first step?

Tags is nice I believe, more like a step already completed. I believe we would have needed tags anyway for sorting posts.

**Comment by KishaniKandasamy** [comment]
https://github.blog/ +1

**Comment by liuxiran** [comment]
> > I prefer https://github.blog/ too. Categorize is a good idea, similar to #470 , we can quickly view the corresponding content by category, so do we still need tags? Or use tags as the first step?
> 
> Tags is nice I believe, more like a step already completed. I believe we would have needed tags anyway for sorting posts.

Agree with you , we need tags any way, so we can use the tag as the first step,  that is to say finish #470 first, and at the same time, make a simple design refer to github blog for our site, in order that we can have a clearer look and feel. We can take action now😊

> Pagination is good, but it has that context switch, staying on same page while browsing is always better

and for this part , browsing is better for view the blogs, and I also perfer this way. But it is not good for Google to generate a snapshot and crawl contents as far as I kown. We need a better user experience, and we also need SEO to get more people to find us through search engines.  looking forward to your opinion on this part, thanks @1502shivam-singh @yzeng25

**Comment by 1502shivam-singh** [comment]
> But it is not good for Google to generate a snapshot and crawl contents as far as I kown. We need a better user experience, and we also need SEO to get more people to find us through search engines.

Hmm, good catch. I just found this [question](https://stackoverflow.com/questions/3084003/will-content-loaded-by-ajax-affect-seo-search-engines) related to this issue. The newer answers around 2015 also seem to highlight this. Might want to check them out. We could go for pagination too if there is any uncertainity, just to be on the safe side.

**Comment by iamayushdas** [comment]
> > But it is not good for Google to generate a snapshot and crawl contents as far as I kown. We need a better user experience, and we also need SEO to get more people to find us through search engines.
> 
> Hmm, good catch. I just found this [question](https://stackoverflow.com/questions/3084003/will-content-loaded-by-ajax-affect-seo-search-engines) related to this issue. The newer answers around 2015 also seem to highlight this. Might want to check them out. We could go for pagination too if there is any uncertainity, just to be on the safe side.

Agree

**Comment by liuxiran** [comment]
> > But it is not good for Google to generate a snapshot and crawl contents as far as I kown. We need a better user experience, and we also need SEO to get more people to find us through search engines.
> 
> Hmm, good catch. I just found this [question](https://stackoverflow.com/questions/3084003/will-content-loaded-by-ajax-affect-seo-search-engines) related to this issue. The newer answers around 2015 also seem to highlight this. Might want to check them out. We could go for pagination too if there is any uncertainity, just to be on the safe side.

Agree, we can use pagination for the first edition, the enhancement of our website is always in progress, once we have confirmed the browser engine can also handle browsing, we can optimise this part

**Comment by guoqqqi** [comment]
> Agree, we can use pagination for the first edition, the enhancement of our website is always in progress, once we have confirmed the browser engine can also handle browsing, we can optimise this part

https://github.blog/ +1
Did we just replace the view more function with a pagination in the first version?
![image](https://user-images.githubusercontent.com/72343596/130912224-5bab0b54-18e8-48c2-a004-91f0c29d0a0a.png)
![image](https://user-images.githubusercontent.com/72343596/130912271-bf6e77ed-bff5-4a3b-ae9d-4f79a089613c.png)

**Comment by iamayushdas** [comment]
> > Agree, we can use pagination for the first edition, the enhancement of our website is always in progress, once we have confirmed the browser engine can also handle browsing, we can optimise this part
> 
> https://github.blog/ +1
> Did we just replace the view more function with a pagination in the first version?
> ![image](https://user-images.githubusercontent.com/72343596/130912224-5bab0b54-18e8-48c2-a004-91f0c29d0a0a.png)
> ![image](https://user-images.githubusercontent.com/72343596/130912271-bf6e77ed-bff5-4a3b-ae9d-4f79a089613c.png)

I guess, you got it right, and that will. make it more accessible.

**Comment by liuxiran** [comment]
![image](https://user-images.githubusercontent.com/2561857/131101269-491332c8-7007-4eb7-b234-01d3c39fef2a.png)

Actually our current way as the image shows also a way of  pagination, we can just keep this way

**Comment by liuxiran** [comment]
Hi all, we have finished the first step of update blog page:

1. add tags for the blog page
pr: https://github.com/apache/apisix-website/pull/538
Effect：
![image](https://user-images.githubusercontent.com/2561857/131770703-712dae7a-4875-488c-9c8a-49ec3e310142.png)
![image](https://user-images.githubusercontent.com/2561857/131770767-980ca867-d970-4e36-a04e-b264a5ef2495.png)
preview: https://deploy-preview-538--apisix.netlify.app

2. remove the recennt posts index links in the blog page
pr: https://github.com/apache/apisix-website/pull/549
Effect：
![image](https://user-images.githubusercontent.com/2561857/131770905-eb5d7405-eaca-4c85-9501-3acbc064fbbc.png)
![image](https://user-images.githubusercontent.com/2561857/131771157-1abb9e33-9343-4de0-974a-4cff90b47d40.png)
preview: https://deploy-preview-549--apisix.netlify.app


3. fix some errors in the blog page
mainly fix can not show Thumbnail for China Mobile Cloud in blog list, already merge, see: https://apisix.apache.org/blog/page/2

As of now we have made changes with the help of the native template, and this is our first step, the native template has little room for optimization in terms of ease of use, please help to review, and comment here your feedback, this will become these will be the focus of our next optimization. Thanks a lot.

cc @1502shivam-singh @Baoyuantop @juzhiyuan @Serendipity96 @yzeng25 @moonming @iamayushdas @KishaniKandasamy

**Comment by iamayushdas** [comment]
> Hi all, we have finished the first step of update blog page:
> 
> 1. add tags for the blog page
>    pr: [feat: add blog tags #538](https://github.com/apache/apisix-website/pull/538)
>    Effect：
>    ![image](https://user-images.githubusercontent.com/2561857/131770703-712dae7a-4875-488c-9c8a-49ec3e310142.png)
>    ![image](https://user-images.githubusercontent.com/2561857/131770767-980ca867-d970-4e36-a04e-b264a5ef2495.png)
>    preview: https://deploy-preview-538--apisix.netlify.app
> 2. remove the recennt posts index links in the blog page
>    pr: [fix: remove Recent posts index in blog page #549](https://github.com/apache/apisix-website/pull/549)
>    Effect：
>    ![image](https://user-images.githubusercontent.com/2561857/131770905-eb5d7405-eaca-4c85-9501-3acbc064fbbc.png)
>    ![image](https://user-images.githubusercontent.com/2561857/131771157-1abb9e33-9343-4de0-974a-4cff90b47d40.png)
>    preview: https://deploy-preview-549--apisix.netlify.app
> 3. fix some errors in the blog page
>    mainly fix can not show Thumbnail for China Mobile Cloud in blog list, already merge, see: https://apisix.apache.org/blog/page/2
> 
> As of now we have made changes with the help of the native template, and this is our first step, the native template has little room for optimization in terms of ease of use, please help to review, and comment here your feedback, this will become these will be the focus of our next optimization. Thanks a lot.
> 
> cc @1502shivam-singh @Baoyuantop @juzhiyuan @Serendipity96 @yzeng25 @moonming @iamayushdas @KishaniKandasamy

It is really lit, thanks for this

**Comment by 1502shivam-singh** [comment]
> As of now we have made changes with the help of the native template, and this is our first step, the native template has little room for optimization in terms of ease of use,

Well technically we can customize this page (any page for that matter), but it would require swizzling the blog related items, these would do -

        yarn swizzle @docusaurus/theme-classic BlogListPage
        yarn swizzle @docusaurus/theme-classic BlogPostItem
        yarn swizzle @docusaurus/theme-classic BlogPostPage
        yarn swizzle @docusaurus/theme-classic BlogTagsListPage
        yarn swizzle @docusaurus/theme-classic BlogTagsPostsPage
        // plus some more to if need to customize the paginator etc.

but it's a step to take once we have some concrete design in place. Maybe sometime later I would experiment and share the output with you all, and based on the responses we could try that.

> please help to review, and comment here your feedback, this will become these will be the focus of our next optimization. Thanks a lot.

LGTM, so now we have to move forward with categorization and related, right ?

**Comment by liuxiran** [comment]
> LGTM, so now we have to move forward with categorization and related, right ?

yes, actually in order to make our blog page have a more clean look quickly, we make a quickly update, and thanks to @Baoyuantop @bzp2010 help, now it has already online, and there is still a lot of room for improvement

* Pagination
* [Improve the tag interaction logic in blog page](https://github.com/apache/apisix-website/issues/554)
* [Bug: extra '|' shown in the blog list](https://github.com/apache/apisix-website/issues/555)
* [Add tags for events page](https://github.com/apache/apisix-website/issues/557)
* other improvement and better design

 welcome to do further design and communication based on your point of interest

**Comment by juzhiyuan** [comment]
You could see the Archive page currently, we still need a good design for pages.

- https://apisix.apache.org/blog/archive/
- https://apisix.apache.org/zh/blog/archive/
