### ISSUE TITLE
discuss: add default text or image for company logo

### ISSUE THREAD

**Issue by foolwc** [apache/apisix-website#492]
**Discuss description**
add default text or image for company logo

**Screenshots of the issue**

![1629477321(1)](https://user-images.githubusercontent.com/13642747/130266221-ad341b3f-5a9c-4cee-97d1-cff4dd1e790b.jpg)

**Comment by liuxiran** [comment]
Default image is good for display, but not friendly in terms of recognition
we' d better add the correct logo for these companies

cc @Serendipity96 to help to provide the corresponding logo images, thanks a lot

**Comment by foolwc** [comment]
Got it.  I could find these companies' logo from their official website and make a PR tomorrow :)

**Comment by liuxiran** [comment]
> Got it. I could find these companies' logo from their official website and make a PR tomorrow :)

so cool, thanks a lot, looking forward to your pr
