### ISSUE TITLE
Bug: there are 10 404 page, we should fix them

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#494]
**Actual Behaviour**

With the help of google search console, we found 10 404 page in our website.

They are:

- [ ] https://apisix.apache.org/docs/downloads/

- [ ] https://apisix.apache.org/subscrbe-guide/

- [ ] https://apisix.apache.org/docs/api/conf/conf.yaml

- [ ] https://apisix.apache.org/users/

- [ ] https://apisix.apache.org/zh/contribute/release/

- [ ] https://apisix.apache.org/users.html

- [ ] https://apisix.apache.org/docs/2fa/

- [ ] https://apisix.apache.org/zh/contribute/2fa/

- [ ] https://apisix.apache.org/docs/helm-chart/apisix/"}

- [ ] https://apisix.apache.org/docs/ingress-controller/getting-started/"}

we should fix them

**Comment by juzhiyuan** [comment]
All fixed
