### ISSUE TITLE
Improve Mobile Usability: Clickable elements too close together

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#502]
**Actual Behaviour**

An error from google search console: In mobile scenarios, clickable elements too close together in our https://apisix.apache.org/zh/docs/apisix/plugins/jwt-auth/    page.

![111](https://user-images.githubusercontent.com/2561857/130547653-1f7eb30f-7ad8-4f07-a0ab-fda32f6783da.jpeg)

**Expected Behaviour**

refer to https://seosandwitch.com/fix-clickable-elements-too-close-together-error/ Step3, we can enlarge the space for click item, that would be more friendly for our website

**Comment by SkyeYoung** [comment]
A question: now the page has a `on the page` block, do we still need the TOC paragraph?
![image](https://user-images.githubusercontent.com/48400568/156094382-ce6a97f1-be1d-42c7-a6c9-56c10cbec092.png)

And do we have any other clickable elements need to be modified?

**Comment by oil-oil** [comment]
> A question: now the page has a `on the page` block, do we still need the TOC paragraph? ![image](https://user-images.githubusercontent.com/48400568/156094382-ce6a97f1-be1d-42c7-a6c9-56c10cbec092.png)
> 
> And do we have any other clickable elements need to be modified?

I think TOC paragraph should be kept, `on the page` block can be removed. This allows the pc and mobile to have the same directory and the changes are smaller.

**Comment by SkyeYoung** [comment]
> I think TOC paragraph should be kept, `on the page` block can be removed. This allows the pc and mobile to have the same directory and the changes are smaller.

I think so, but this maybe need a futher discussion.

**Comment by juzhiyuan** [comment]
> > A question: now the page has a `on the page` block, do we still need the TOC paragraph? ![image](https://user-images.githubusercontent.com/48400568/156094382-ce6a97f1-be1d-42c7-a6c9-56c10cbec092.png)
> > And do we have any other clickable elements need to be modified?
> 
> I think TOC paragraph should be kept, `on the page` block can be removed. This allows the pc and mobile to have the same directory and the changes are smaller.

AFAIK, we will remove all outlines from markdown files, could check apache/apisix's issue 😄

**Comment by SkyeYoung** [comment]
> AFAIK, we will remove all outlines from markdown files, could check apache/apisix's issue 😄

And, "Back to TOC" also need to be removed.

**Comment by juzhiyuan** [comment]
Yes, e.g., https://apisix.apache.org/docs/apisix/architecture-design/#route

![image](https://user-images.githubusercontent.com/2106987/159410601-c945ba75-9db7-4d6f-8119-4d3bc2c85e4c.png)

**Comment by saurabhsingh-7** [comment]
Hello,

I'm eager to help fix the "Clickable Elements Too Close Together" issue in Google Search Console. I've analyzed the problem and am ready to start. Here's my plan:

Identify affected elements.
Implement mobile-friendly adjustments.
Thoroughly test for a solution.
Please assign me this task so I can begin working on it. Feel free to reach out for further discussion.

Thank you!
Saurabh Singh
saurabhsinghryan@gmail.com
