### ISSUE TITLE
Redesign the showcase page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#519]
**Expected Behaviour**

Redesign our showcase in a new page

reference:
* http://airflow.apache.org/use-cases/
* http://flex.apache.org/community-showcase.html
* http://cloudstack.apache.org/users.html

**Comment by 1502shivam-singh** [comment]
Something I always had in mind but didn't execute, so as to not to disturb the existing work-flow of adding company logos. 
To add to this I personally always thought that our showcase section on landing page was always too much complicated for no reason, as you can see below.

![image](https://user-images.githubusercontent.com/57267960/130968557-697146e0-8f0a-4e41-a58c-a5fb2d9cecc8.png)

There are just too many logos in there, often leading to the logos of companies, that are well known worldwide and have a good brand name, getting lost in them. The main reason of this section is to add a notion of trust in the user for our product. We might not succeed in this if the brand names that have giant userbases get lost in this large collection of logos on an initial view.

What I think would be better is showing logos of only a few selected brands (around 8-10) that are well known and have a nice large userbase. This would be more focussed, and then we can link to the showcase page (as per issue) to mention all the user stories by companies that use APISIX (here we can go in detail and add all companies that use APISIX)

As always, some examples - 

- [Stripe](https://stripe.com/en-in)
- [Flutter](https://flutter.dev/)
- [Mono color logos style - Figma](https://www.figma.com/)

Also, Flutter has a nice showcase page - [Flutter showcase](https://flutter.dev/showcase)

**Comment by liuxiran** [comment]
Your design inspiration is especially valuable, and please refer https://github.com/apache/apisix-website/pull/547#issuecomment-910489289 for more details, thanks a lot

**Comment by 1502shivam-singh** [comment]
So we have something like showing only logos of established and well known companies on the home page and have a hyperlink their to link to the users page (Along with on the navbar). 

Now, once back I actually did a prototype of this. Ignore logo padding issues for now, will change that. Also, I actually put logos on the basis ones that kinda looked cool 😅, so maybe they would need replacements with other bigger players (as per the market you are targeting. On a sidenote, I have actually observed companies putting these logos on the basis of the country where the website is visited so as to help in local market penetration)

![image](https://user-images.githubusercontent.com/57267960/131758853-857f716e-fada-4b73-ac4d-bc180ae3ce5f.png)

**Comment by liuxiran** [comment]
> ![image](https://user-images.githubusercontent.com/57267960/131758853-857f716e-fada-4b73-ac4d-bc180ae3ce5f.png)

We need to put all logos on one page expect for home page, only show logos is also a good way👍 
cc @bzp2010 to have a look and improve our showcase page

https://github.com/apache/apisix-website/pull/547

**Comment by SkyeYoung** [comment]
Should this be closed by https://github.com/apache/apisix-website/pull/547? Or do we need redesign it again?
