### ISSUE TITLE
Bug: broken link in real-ip and gzip plugin page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#544]
**Actual Behaviour**

There is a broken link in both `real-ip` and `gzip` plugin page

![image](https://user-images.githubusercontent.com/2561857/131461861-7e9b641a-e9e0-4af9-a6bc-b59a29220e22.png)

![image](https://user-images.githubusercontent.com/2561857/131461916-c68ab282-cc2c-44d2-b362-24756bec374d.png)

the right link should be: `/zh/docs/apisix/how-to-build/#步骤6：为-apache-apisix-构建-openresty` for zh and `https://apisix.apache.org/docs/apisix/how-to-build/#step-6-build-openresty-for-apache-apisix` for en

**Comment by huang-x-h** [comment]
i want to fixed it, but the docs is in https://github.com/apache/apisix/tree/master/docs, am i right? @liuxiran

**Comment by bzp2010** [comment]
> i want to fixed it, but the docs is in https://github.com/apache/apisix/tree/master/docs, am i right? @liuxiran

@huang-x-h Yes, the document is in that repo.

**Comment by huang-x-h** [comment]
`gzip` / `real-ip` have no zh docs, so it fallback to en, so we need add zh docs for this two plugins ? @bzp2010

**Comment by bzp2010** [comment]
@huang-x-h If you are willing to make this contribution, we are very welcome. At the same time, if you need any help, you can @ me.

**Comment by juzhiyuan** [comment]
fixed.
