### ISSUE TITLE
Improve the tag interaction logic in blog page 

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#554]
Awesome, thanks @Baoyuantop .

and there are something would make this feature better to use, as @1502shivam-singh pointed in https://github.com/apache/apisix-website/pull/553#issuecomment-913048731
> This, as is understandable can become little confusing. So I guess an option could be keeping the sidebar static, not changing on clicking on tags, just changing the background of the tag clicked to red.

this suggestion would be a better choice, 

and more details :
* when user choose a tag, e.g. technology,  this tag should be marked color red, and all the posts contains technology tag should be listed.
* when user choose two tags, e.g. technology and news, these two tags should be marked color red, and all the posts contains technology should be list, and all the posts contains news tag should be list too. Attention that, the posts contains both  technology and news tags, should be only list one time.
* when user choose `All` tag, clear all other tags selected, and list all posts.

what do you think?

_Originally posted by @liuxiran in https://github.com/apache/apisix-website/issues/553#issuecomment-913055305_

**Comment by Baoyuantop** [comment]
In general, these are two problems that need to be resolved:

1. Find a method or API to get all blog data in `BlogListPage` and `BlogTagsPostPage`.
At present, the data of tags comes from the list page on the right side of it. In BlogPostPage, I used cancel pagination to get all the blog data. But I didn’t find a way to get it in BlogTagsPostPage, which also caused the display of tags to appear abnormal after selecting a tag.

2. Find a way to filter multiple tags at the same time in `docusaurus`.This can better support users to view blogs under multiple tags at the same time.
