### ISSUE TITLE
Bug: extra '|' shown in the blog list

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#555]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/2561857/132151397-d9ddf7e0-126b-4752-89a2-f1c46ab27a1f.png)

![image](https://user-images.githubusercontent.com/2561857/132151493-d55d1244-423f-4273-9416-4ffcf21147a2.png)

There is an extra '|' shown in the blog list

we should remove it.

**Comment by Baoyuantop** [comment]
Need to add judgment for the existence of `|`.

**Comment by liuxiran** [comment]
> Need to add judgment for the existence of `|`.

yes, would you like to fix it?
