### ISSUE TITLE
The Blog tags is missing

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#562]
**Actual Behaviour**

1. Visit https://apisix.apache.org/blog/
2. Click Tags -> practical case
3. Before clicking:
![image](https://user-images.githubusercontent.com/2106987/132275923-feea4b9d-7b1a-4386-803c-7acee8c2fa36.png)

4. After clicking:
![image](https://user-images.githubusercontent.com/2106987/132275914-6e678401-3fa7-4e58-9faa-8191a34a95ea.png)

**Expected Behaviour**

It should not be hidden.

**Comment by liuxiran** [comment]
refer  https://github.com/apache/apisix-website/issues/554 for more details
