### ISSUE TITLE
blog: Failed to load article

### ISSUE THREAD

**Issue by membphis** [apache/apisix-website#563]
URI: https://apisix.apache.org/blog/2020/08/22/new-website

![image](https://user-images.githubusercontent.com/6814606/132278695-3c10c486-2797-4dce-9533-e961c6ee1b58.png)

**Comment by liuxiran** [comment]
Hi @membphis , this article shows just the what it originally wrote, and it seems more like a develop guide, so how about remove this article to our website develop guide and not shown in our blog list?

**Comment by bzp2010** [comment]
According to the source code of the article, this is what it looks like. But I also think it's in the wrong place.

**Comment by membphis** [comment]
I think we should delete this article.

**Comment by bzp2010** [comment]
+1 agree

**Comment by liuxiran** [comment]
ok, that's a deal
