### ISSUE TITLE
bug: tags link broken in release page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#564]
**Actual Behaviour**

When click tag on release page, it will redirect to 404 page, we should update these links

![image](https://user-images.githubusercontent.com/2561857/132284804-25a1158e-035a-446a-8252-3508284645c5.png)

![image](https://user-images.githubusercontent.com/2561857/132284718-c2013a13-6a2a-42bb-a3bf-f60a6f230606.png)

**Comment by Baoyuantop** [comment]
I realized that I modified the theme components in #553, and these components are used in `events`、`releases` and `articles`, so they are affected, and they should be dealt with in the theme file.
