### ISSUE TITLE
bug: tags behave abnormally

### ISSUE THREAD

**Issue by yzeng25** [apache/apisix-website#567]
**Actual Behaviour**

Tags on http://apisix.apache.org/events page have unusual behaviors. When click on the `technology` tag or the `all` tag on this page, it redirects to http://apisix.apache.org/blog/tags/technology.

**Expected Behaviour**

Click on the `technology` tag or the `all` tag on this page, it should stay in the events and return results under `all` tag or `technology` tag. Besides, it should redirect to something like `http://apisix.apache.org/events /tags/technology`.

 

**Steps to reproduce it**

1. visit http://apisix.apache.org/events
2. click  `technology` tag or the `all` tag
3. redirect to http://apisix.apache.org/blog/tags/technology

**Screenshots of the issue**
![Snipaste_2021-09-07_17-50-09](https://user-images.githubusercontent.com/36651058/132324578-7801adb2-56ee-47fa-b99d-2cbcb25ff50c.png)
![Snipaste_2021-09-07_17-50-37](https://user-images.githubusercontent.com/36651058/132324600-10dbc165-c401-40b5-b92a-c41e0a9553fb.png)

**Comment by yzeng25** [comment]
Hi @liuxiran @bzp2010, could you take a look?

**Comment by liuxiran** [comment]
this can be partly resolved by https://github.com/apache/apisix-website/pull/565
