### ISSUE TITLE
CI: Check broken links CI Cancelled after 360m

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#570]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/2561857/132468303-d6133f34-517f-4ee4-8345-81f515360978.png)

need to check this ci item.

**Comment by bzp2010** [comment]
Update: A timeout has been added to Axios to place the CI timeout issue.

**Comment by juzhiyuan** [comment]
> Update: A timeout has been added to Axios to place the CI timeout issue.

Then this issue has been resolved? @bzp2010

**Comment by bzp2010** [comment]
> > Update: A timeout has been added to Axios to place the CI timeout issue.
> 
> Then this issue has been resolved? @bzp2010

Yes
