### ISSUE TITLE
Bug: broken link in plugins prometheus page

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#572]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/2561857/132488080-1f8b41ab-1fd7-4b4b-a30e-ead5e9cfb50e.png)

![image](https://user-images.githubusercontent.com/2561857/132488170-be403059-a428-49a8-9b15-20d981f3d055.png)

**Comment by KishaniKandasamy** [comment]
but this link works fine from the github preview So
For this JSON file, we could use https://github.com/apache/apisix/blob/master/docs/assets/other/json/apisix-grafana-dashboard.json directly as the relative link causes broken direction .

**Comment by Baoyuantop** [comment]
I think this may be caused by batch processing of the links in the markdown file when building the site.
