### ISSUE TITLE
Broken image link on the Post page

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#579]
**Actual Behaviour**

see https://apisix.apache.org/articles/The-Appeal-of-OpenSource/

![image](https://user-images.githubusercontent.com/2106987/132669336-23215f01-082a-49c3-b94d-022f2f15f94f.png)

**Comment by Baoyuantop** [comment]
Where is the entry for `articles` on our website?🤔

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-website/tree/master/website/articles

**Comment by bzp2010** [comment]
> Where is the entry for `articles` on our website?🤔

Hi, @Baoyuantop.
We don't have a direct entry to the articles module. It's just a repository of articles. All their external links come from the index articles of Apachecon Asia 2021 in the blog module.
