### ISSUE TITLE
UI: APISIX architecture image size distorted

### ISSUE THREAD

**Issue by 1502shivam-singh** [apache/apisix-website#581]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/57267960/132698440-f0a6943d-e912-4794-aeda-3ea2e93ee6ff.png)

**Steps to reproduce it**

Visit website. 

Some CSS mishap i guess.

**Comment by Baoyuantop** [comment]
There seems to be an extra `width` on this `img` element.
