### ISSUE TITLE
Support PR preview

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-website#582]
Feature request:

we used Netlify to provide pr preview link, some one may noticed that we remove this feature, yes , we need to find a  stable and more cost-effective way, proposals Welcome.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/135939640-e6d3d030-0357-41f0-8aa2-921f597e0280.png)

https://github.com/apache/apisix-website/actions/runs/1305721808

**Comment by bzp2010** [comment]
According to github actions rules, The contributor's PR cannot access the secret settings in the main repop, so relying on the workflow triggered in the PR cannot use these secrets to deploy the site.

**Comment by juzhiyuan** [comment]
Yes, will find out another way 🤔

**Comment by juzhiyuan** [comment]
https://docusaurus.io/docs/deployment#deploying-to-hostman

**Comment by juzhiyuan** [comment]
consider closed because we use Netlify back 😄
