### ISSUE TITLE
Double slash in URL

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#589]
**Actual Behaviour**

![图片](https://user-images.githubusercontent.com/2106987/133033779-e99ef3e6-96cb-4f19-829c-9a218d179498.png)

https://apisix.apache.org/docs/apisix/2.8/plugins/cors/

**Issue details**

URLs that contain a double slash (after the domain part).

Most servers are set up to ignore a double slash in the URL path. However, such URLs may be confusing for search engines as they will be interpreted as stand-alone URLs, which can result in duplicate content issues.

**How to fix**

Review the URLs in this report and remove the unnecessary double slashes from their permalinks.

After that, you can check the internal backlinks to the URLs with a double slash and point them to the corrected URL. This will prevent some unnecessary redirects on your website.

**Comment by liuxiran** [comment]
cc @bzp2010 to have a look, thanks

**Comment by juzhiyuan** [comment]
Just checked and has been fixed.
