### ISSUE TITLE
meta descriptions too short

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#592]
**Issue details**

Google sometimes uses <meta> tag content to generate snippets, if they think they give users a more accurate description than can be taken directly from the page content.

Besides, Facebook, for example, will use <meta> tag content for link preview if the page has no 'og:description' tag.

A short meta description may not summarize the content of your page in the best possible way.

![图片](https://user-images.githubusercontent.com/2106987/133035159-fdfba2ec-2af5-49f3-bd54-69aea63f1748.png)

Files: 
[duplicates.csv](https://github.com/apache/apisix-website/files/7151936/duplicates.csv)

**How to fix**

A general recommendation today is to keep your page description between 110 and 160 characters, although Google can sometimes show longer snippets.

**Comment by juzhiyuan** [comment]
Google recommendation: https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets?hl=en&visit_id=637671116441869814-731571163&rd=1

**Comment by SkyeYoung** [comment]
This was solved in #1225 . Now the website builder can skip the comment and get a more useful description.

I think we can close this issue and reopen a new one, if the description of some pages is not SEO friendly.
