### ISSUE TITLE
bug: wrong link

### ISSUE THREAD

**Issue by membphis** [apache/apisix-website#6]
change to new apache link.

![image](https://user-images.githubusercontent.com/6814606/67786809-75d83a00-faaa-11e9-8ee5-129447b64681.png)

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/67788861-02382c00-faae-11e9-8690-cba7df123196.png)

ditto

**Comment by juzhiyuan** [comment]
fixed
