### ISSUE TITLE
Integrate APISIX autogenerated docs with the website

### ISSUE THREAD

**Issue by sshniro** [apache/apisix-website#61]
The docs currently support docsify. Therefore in order to showcase docs, I assume the following steps should be completed.
1. Create a Tab in website for docs
2. Update the Github action to trigger on tag realease
3. Package the HTML content inside the website (make it compatible with Hugo)

**Comment by sshniro** [comment]
@juzhiyuan shall I will start with appending a `docs` nav element and trying to embed the autogenerated docs from the master branch to check if this is doable with Hugo?

**Comment by juzhiyuan** [comment]
Yep, go ahead please:D
