### ISSUE TITLE
Apache APISIX's official webpage is at risk of hijacking

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix-website#74]
Apache APISIX's official webpage is at risk of hijacking

Phenomena.
1. search the Apache APISIX website through Baidu or Google, the default is to use the HTTP protocol to access.
![image](https://user-images.githubusercontent.com/3816205/93440497-0fe2e400-f902-11ea-9563-506791b8d8d3.png)

Solution.
1. if it's an http request, reply to the 302 bounce response to jump to the https page
2. add response header for all http responses: `Strict-Transport-Security: max-age=172800` to ensure that subsequent users accessing the apisix website will use the https protocol by default.

**Comment by juzhiyuan** [comment]
need to create an infra ticket if this issue should be fixed.
