### ISSUE TITLE
Update Homepage

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#77]
![image](https://user-images.githubusercontent.com/2106987/94354337-bd958600-00ac-11eb-8995-9033dfc2a13c.png)

**Comment by idontknowjs** [comment]
@juzhiyuan can you please translate these, tried using google translate. But it's not translating accurately, thanks!

**Comment by moonming** [comment]
ping @juzhiyuan

**Comment by juzhiyuan** [comment]
sure

**Comment by juzhiyuan** [comment]
**Translation**
1. The Logo changed to a white silhouette, preferably vector graphics.
2. Copywriting needs to be simplified.
3. Buttons need icons.
4. Requires mouse hover highlighting.

BTW, we are working on migration[1], but we could still continue resolving this one.

[1] https://github.com/apache/apisix-website/pull/153
