### ISSUE TITLE
add apisix/doc to website for better view

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-website#78]
In https://github.com/apache/apisix/pull/1724, sshniro use docsify to build a website for the doc, but I think we didn't actually present that link to users and he hasn't maintained that repo anymore.

I think maybe we could directly add the doc here. I just don't know how to sync apisix/doc here.

**Comment by Yiyiyimu** [comment]
I think netlify support this feature: [use multiple repo to build one website](https://community.netlify.com/t/support-guide-can-i-deploy-multiple-repositories-in-a-single-site/179). I'm not sure if docusaurus supports it

**Comment by membphis** [comment]
welcome to make a try ^_^

**Comment by juzhiyuan** [comment]
I prefer migrating all docs from the apisix's repo to here, not sure if it's ok to do so.

**Comment by sober-wang** [comment]
Maybe our documentation should marge to [APISIX Home Website](https://apisix.apache.org/docs/subscrbe-guide/)
We should learning it  from [HBase](https://hbase.apache.org/) web site.

**Comment by juzhiyuan** [comment]
I'm working on this issue, thanks for your advice.
