### ISSUE TITLE
Broken links on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix-website#95]
Most of the links on the download page are broken:

http://apisix.apache.org/docs/downloads/

Looks like the page has not been published correctly

**Comment by juzhiyuan** [comment]
No, there doesn't have docs anymore. Maybe i should republish the asf branch cleanly.

**Comment by sebbASF** [comment]
Note that the page is linked from http://apisix.apache.org in the second Downloads link, so that needs to be fixed to agree with the first link

**Comment by juzhiyuan** [comment]
Oh i know what happened, Thanks for your report.
